// lib/utils/localization/ar_sa.dart

const Map<String, String> arSA = {
  // General
  'general.appTitle': 'مذكرة الدواء',
  'general.save': 'حفظ',
  'general.cancel': 'إلغاء',
  'general.delete': 'حذف',
  'general.edit': 'تعديل',
  'general.add': 'إضافة',
  'general.confirm': 'تأكيد',
  'general.success': 'نجاح',
  'general.error': 'خطأ',
  'general.loading': 'جار التحميل...',
  'general.requiredField': 'هذا الحقل مطلوب',
  'general.done': 'تم',

  // Auth
  'auth.login': 'تسجيل الدخول',
  'auth.signup': 'إنشاء حساب',
  'auth.logout': 'تسجيل الخروج',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.loginButton': 'تسجيل الدخول',
  'auth.signupButton': 'إنشاء حساب',
  'auth.loginErrorTitle': 'فشل تسجيل الدخول',
  'auth.signupErrorTitle': 'فشل إنشاء الحساب',
  'auth.unknownError': 'حدث خطأ غير معروف.',
  'auth.or': 'أو',
  'auth.noAccount': 'ليس لديك حساب؟ سجل الآن',
  'auth.haveAccount': 'لديك حساب بالفعل؟ سجل الدخول',

  // Home / Medicine List
  'home.title': 'أدويتي',
  'home.addMedicine': 'إضافة دواء جديد',
  'home.noMedicines': 'لم تتم إضافة أدوية بعد. اضغط على + لإضافة واحد!',
  'home.confirmDeleteTitle': 'حذف الدواء',
  'home.confirmDeleteContent': 'هل أنت متأكد من رغبتك في حذف {medicineName}؟',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'إضافة دواء',
  'addMedicine.titleEdit': 'تعديل الدواء',
  'addMedicine.nameLabel': 'اسم الدواء',
  'addMedicine.nameHint': 'مثال: باراسيتامول',
  'addMedicine.typeLabel': 'نوع/فئة الدواء',
  'addMedicine.typeHint': 'مثال: حبوب، شراب، حقن',
  'addMedicine.dosageLabel': 'كمية الجرعة',
  'addMedicine.dosageHint': 'مثال: 1، 2، 500',
  'addMedicine.dosageUnitLabel': 'وحدة الجرعة',
  'addMedicine.dosageUnitHint': 'مثال: قرص، مل، مج',
  'addMedicine.frequencyLabel': 'التكرار',
  'addMedicine.frequencyHint': 'مثال: يوميًا، مرتين في اليوم',
  'addMedicine.durationLabel': 'المدة (أيام)',
  'addMedicine.durationHint': 'مثال: 7، 14، 30 (0 للاستمرار)',
  'addMedicine.whenToTakeLabel': 'وقت التناول / ملاحظات',
  'addMedicine.whenToTakeHint': 'مثال: مع الطعام، قبل النوم',
  'addMedicine.startDateLabel': 'تاريخ البدء',
  'addMedicine.endDateLabel': 'تاريخ الانتهاء (اختياري)',
  'addMedicine.selectDate': 'اختر التاريخ',
  'addMedicine.selectTime': 'اختر الوقت',
  'addMedicine.timesLabel': 'مرات في اليوم',
  'addMedicine.addTime': 'إضافة وقت',
  'addMedicine.notesLabel': 'ملاحظات إضافية (اختياري)',
  'addMedicine.notesHint': 'مثال: يحفظ في مكان بارد',
  'addMedicine.enableNotificationsLabel': 'تفعيل تذكير الجرعات',
  'addMedicine.errorNumeric': 'الرجاء إدخال رقم صحيح',
  'addMedicine.addMedicine': 'إضافة دواء',
  'addMedicine.save': 'حفظ',
  'addMedicine.name': 'اسم الدواء',
  'addMedicine.addMedicineHint': 'اسم الدواء (مثال: باراسيتامول)',
  'addMedicine.dosage': 'الجرعة',
  'addMedicine.dosageHint2': 'الكمية (مثال: 500)',
  'addMedicine.dosageUnit': 'الوحدة (مثال: مج)',
  'addMedicine.category': 'الفئة',
  'addMedicine.frequency': 'التكرار والمدة',
  'addMedicine.selectDoseTimes': 'اختر أوقات الجرعة',
  'addMedicine.times': 'مرة (مرات) محددة',
  'addMedicine.selectDuration': 'اختر المدة',
  'addMedicine.days': 'يوم (أيام)',
  'addMedicine.whenToTake': 'وقت التناول',
  'addMedicine.beforeFood': 'قبل الطعام',
  'addMedicine.afterFood': 'بعد الطعام',
  'addMedicine.notifications': 'الإشعارات',
  'addMedicine.enableNotifications': 'تفعيل تذكير الجرعات',
  'addMedicine.receiveNotification': 'استلام إشعار قبل 5 دقائق من كل جرعة',
  'addMedicine.doseTimesPickerTitle': 'اختر أوقات الجرعة',
  'addMedicine.done': 'تم',

  // Medicine Controller Messages
  'medicine.addSuccess': 'تمت إضافة الدواء بنجاح.',
  'medicine.updateSuccess': 'تم تحديث الدواء بنجاح.',
  'medicine.deleteSuccess': 'تم حذف الدواء بنجاح.',
  'medicine.errorNeedTime': 'الرجاء اختيار وقت واحد على الأقل.',
  'medicine.saveMedicineSuccess': 'تم حفظ الدواء بنجاح.',
  'medicine.saveMedicineError': 'خطأ',
  'medicine.saveMedicineErrorMessage': 'فشل في حفظ الدواء: {e}',
  'medicine.updateMedicineSuccess': 'تم تحديث الدواء بنجاح.',
  'medicine.updateMedicineError': 'خطأ',
  'medicine.updateMedicineErrorMessage': 'فشل في تحديث الدواء: {e}',
  'medicine.deleteMedicineSuccess': 'تم حذف الدواء بنجاح.',
  'medicine.deleteMedicineError': 'خطأ',
  'medicine.deleteMedicineErrorMessage': 'فشل في حذف الدواء: {e}',
  'medicine.withFood': 'مع الطعام',
  'medicine.deleteMedicineSuccessMessage': 'تم حذف الدواء بنجاح.',
  'medicine.saveMedicineSuccessMessage': 'تم حفظ الدواء بنجاح.',

  // Settings Page
  'settings.title': 'الإعدادات',
  'settings.language': 'اللغة',
  'settings.selectLanguage': 'اختر اللغة',
  'settings.profile': 'الملف الشخصي',

  // Introduction Screen
  'introduction.skip': 'تخطي',
  'introduction.done': 'تم',
  'introduction.next': 'التالي',

  // Filter
  'filter.allTypes': 'كل الأنواع',
  'filter.uncategorized': 'غير مصنف',
  'filter.searchHint': 'بحث عن الأدوية...',
  'filter.noResultsForSearchAndType': 'لا توجد نتائج لـ "{query}" في {type}',
  'filter.noResultsForSearch': 'لا توجد نتائج لـ "{query}"',
  'filter.noResultsForType': 'لا توجد نتائج للنوع "{type}"',

  // Medicine Card
  'card.treatmentCompleted': 'العلاج مكتمل',
  'card.nextDoseN_A': 'الجرعة التالية: غير متوفر',
  'card.todayAt': 'اليوم في',
  'card.tomorrowAt': 'غدًا في',
  'card.at': 'في',
  'card.nextDose': 'الجرعة التالية:',
  'card.frequency.onceDaily': 'مرة واحدة يوميًا',
  'card.frequency.twiceDaily': 'مرتين يوميًا',
  'card.frequency.thriceDaily': 'ثلاث مرات يوميًا',
  'card.frequency.timesDaily': '{count} مرات يوميًا',
  'addMedicine.nameLabelText': 'الاسم',
  'addMedicine.dosageLabelText': 'الجرعة',
  'addMedicine.dosageQuantityHint': 'الكمية (مثال: 500)',
  'addMedicine.categoryLabel': 'الفئة',
  'addMedicine.frequencyDurationLabel': 'التكرار والمدة',
  'addMedicine.selectDoseTimesPlaceholder': 'اختر أوقات الجرعة',
  'addMedicine.doseTimesBottomSheetTitle': 'اختر أوقات الجرعة',
  'addMedicine.timesSelectedInfo': '{count} وقت (أوقات) محددة',
  'addMedicine.selectDurationPlaceholder': 'اختر المدة',
  'addMedicine.durationSelectedInfo': '{count} يوم (أيام)',
  'addMedicine.whenToTakeLabelText': 'وقت التناول',
  'addMedicine.beforeFoodOption': 'قبل الطعام',
  'addMedicine.afterFoodOption': 'بعد الطعام',
  'addMedicine.notificationsSectionLabel': 'الإشعارات',
  'addMedicine.notificationSubtext': 'استلام إشعار قبل 5 دقائق من كل جرعة',
  'addMedicine.durationPickerTitle': 'اختر المدة (بالأيام)',
  'addMedicine.durationPickerItemText': '{days} يوم (أيام)',
  'addMedicine.timesSelected': 'مرات محددة',
  'addMedicine.notificationsLabel': 'الإشعارات',
  'addMedicine.enableDoseReminders': 'تفعيل تذكير الجرعات',
  'addMedicine.remindersSubtext': 'استلام إشعار قبل 5 دقائق من كل جرعة',
  'addMedicine.deleteMedicine': 'حذف الدواء',

  // Profile Page
  'personal_info': 'المعلومات الشخصية',
  'preferences': 'التفضيلات',
  'about_app': 'حول التطبيق',
  'app_version': 'إصدار التطبيق',
  'privacy_policy': 'سياسة الخصوصية',
  'developer': 'المطور: فرقان عاكف إسلك',
  'noEmail': 'لم يتم العثور على بريد إلكتروني',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'حذف الحساب',
  'profile.deleteAccountImportantText':
      'هل أنت متأكد من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
  'profile.cancel': 'إلغاء',
  'profile.delete': 'حذف',
  'profile.errorDeletingAccount': 'خطأ في حذف الحساب',
  'profile.deleteAccountButton': 'حذف الحساب',

  // Profile Page
  'logout': 'تسجيل الخروج',
  'account': 'الحساب',

  // Blog Page
  'Blog': 'مدونة',
  'Bir hata oluştu.': 'حدث خطأ.',
  'Blog yazısı bulunamadı.': 'لم يتم العثور على مقالات في المدونة.',
  'Şuan blog yok': 'لا توجد مدونات متاحة',
  'pills': 'حبوب',
  'health': 'الصحة',
  'lifeStyle': 'نمط الحياة',

  // Privacy Policy
  'privacy_policy_content':
      '<h3>تذكير الدواء - سياسة الخصوصية</h3><br><p><b>استخدام المعلومات الشخصية:</b><br>يلتزم تطبيقنا بحماية خصوصية مستخدمينا. في تطبيق تذكير الدواء الخاص بنا، نقوم بجمع المعلومات الضرورية (البريد الإلكتروني ومعلومات الملف الشخصي وخطط الدواء) لتتبع الأدوية والتذكيرات. يتم استخدام هذه المعلومات لتقديم وتحسين خدمتنا وعدم مشاركتها مع أطراف ثالثة.</p><br><p><b>تخزين البيانات والأمان:</b><br>يتم تخزين بيانات المستخدم الخاصة بك على خوادم آمنة بتنسيق مشفر. تتم حماية معلومات الدواء الخاصة بك وبياناتك الشخصية بموجب تدابير أمنية قوية. فقط الموظفين الضروريين يمكنهم الوصول إلى بياناتك.</p><br><p><b>حقوق المستخدم:</b><br>يحق للمستخدمين عرض حساباتهم وبياناتهم أو تعديلها أو حذفها في أي وقت. عندما تحذف حسابك، تتم إزالة جميع بياناتك نهائيًا من نظامنا.</p><br><p><b>ملفات تعريف الارتباط والتتبع:</b><br>قد يستخدم تطبيقنا ملفات تعريف الارتباط لتحسين تجربة المستخدم. تخزن ملفات تعريف الارتباط هذه تفضيلات المستخدم وبيانات استخدام التطبيق. يمكنك تعطيل ملفات تعريف الارتباط من إعدادات المتصفح الخاص بك إذا كنت ترغب في ذلك.</p><br><p><b>الإشعارات:</b><br>يرسل تطبيقنا إشعارات فقط لتذكيرات الدواء المعتمدة من قبل المستخدم. لن تتلقى إشعارات غير مرغوب فيها ويمكنك تعطيل الإشعارات من قسم الإعدادات.</p><br><p><b>التغييرات:</b><br>قد يتم تحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سيتم إخطار المستخدمين عند إجراء تغييرات مهمة. باستخدام تطبيقنا، فإنك توافق على هذه الشروط.</p><br><p><b>الاتصال:</b><br>يرجى الاتصال بنا إذا كانت لديك أي أسئلة حول سياسة الخصوصية الخاصة بنا.</p>',

  // Introduction Page
  "introduction.page1.title": "تناول دواءك في الوقت المحدد، حافظ على صحتك",
  "introduction.page1.description":
      "من السهل نسيان مواعيد الدواء في زحمة الحياة. مع تطبيقنا، لن تفوت أي جرعة بعد الآن. حدد دواءك، والوقت، والمدة – وسنذكرك في الوقت المناسب.",
  "introduction.page1.tip":
      "الصحة تبدأ بجرعة من الاهتمام تؤخذ في الوقت المناسب.",

  "introduction.page2.title": "تابع صحتك، ابق على اطلاع",
  "introduction.page2.description":
      "نحن لا نذكرك فقط، بل نقدم لك أيضًا معلومات مفيدة عن صحتك. عزز عاداتك الصحية اليومية من خلال مقالات المدونة المدعومة من الخبراء.",
  "introduction.page2.tip": "معلومة صغيرة يمكن أن تحدث فرقًا كبيرًا.",

  "introduction.page3.title": "مفتوح للعالم، مخصص لك",
  "introduction.page3.description":
      "تطبيقنا متاح للجميع بدعم 16 لغة. مع واجهة سهلة الاستخدام، أضف دواءك بلمسات قليلة واجعل حياتك أسهل.",
  "introduction.page3.tip": "الصحة عالمية، ونحن كذلك.",

  "introduction.back": "رجوع",
  "introduction.start": "ابدأ",

  // Register Page
  "register.register_to_medreminder_app": "التسجيل في تطبيق مذكر الدواء",
  "register.already_have_an_account": "هل لديك حساب بالفعل؟ ",
  "register.sign_in": "تسجيل الدخول",
  "register.full_name": "اسمك الكامل",
  "register.surname": "لقبك",
  "register.your_email": "بريدك الإلكتروني",
  "register.type_your_password": "اكتب كلمة المرور",
  "register.re_type_your_password": "أعد كتابة كلمة المرور",
  "register.register": "تسجيل",
  "register.fill_all_fields": "يرجى ملء جميع الحقول",
  "register.password_not_match": "كلمات المرور غير متطابقة",
  "register.error_occurred": "حدث خطأ",

  // Login Page
  "login.invalid_email": "عنوان بريد إلكتروني غير صالح",
  "login.user_disabled": "تم تعطيل المستخدم",
  "login.email_already_in_use":
      "عنوان البريد الإلكتروني هذا قيد الاستخدام بالفعل",
  "login.wrong_password": "المعلومات التي أدخلتها غير صحيحة",
  "login.email_not_verified": "يرجى التحقق من عنوان بريدك الإلكتروني أولاً",
  "login.operation_not_allowed": "هذه العملية غير مسموح بها",
  "login.error_occurred": "حدث خطأ",
  "login.error_occured_google": "حدث خطأ أثناء تسجيل الدخول باستخدام جوجل",
  "login.please_enter_your_email": "يرجى إدخال عنوان بريدك الإلكتروني",
  "login.password_reset_email_sent":
      "تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور",
  "login.login_into_your_account": "تسجيل الدخول إلى حسابك",
  "login.dont_have_an_account": "ليس لديك حساب؟ ",
  "login.sign_up": "سجل",
  "login.your_email": "بريدك الإلكتروني",
  "login.type_your_password": "اكتب كلمة المرور",
  "login.login": "تسجيل الدخول",
  "login.forgot_password": "نسيت كلمة المرور؟",
  "login.or": "أو",
  "login.login_with_google": "تسجيل الدخول باستخدام جوجل",
};
