const Map<String, String> bnBD = {
  // General
  'general.appTitle': 'ঔষধ রিমাইন্ডার',
  'general.save': 'সংরক্ষণ করুন',
  'general.cancel': 'বাতিল করুন',
  'general.delete': 'মুছুন',
  'general.edit': 'সম্পাদনা করুন',
  'general.add': 'যোগ করুন',
  'general.confirm': 'নিশ্চিত করুন',
  'general.success': 'সফল',
  'general.error': 'ত্রুটি',
  'general.loading': 'লোড হচ্ছে...',
  'general.requiredField': 'এই ক্ষেত্রটি প্রয়োজনীয়',
  'general.done': 'সম্পন্ন',

  // Auth
  'auth.login': 'লগইন',
  'auth.signup': 'নিবন্ধন করুন',
  'auth.logout': 'লগআউট',
  'auth.email': 'ইমেইল',
  'auth.password': 'পাসওয়ার্ড',
  'auth.loginButton': 'লগইন করুন',
  'auth.signupButton': 'নিবন্ধন করুন',
  'auth.loginErrorTitle': 'লগইন ব্যর্থ হয়েছে',
  'auth.signupErrorTitle': 'নিবন্ধন ব্যর্থ হয়েছে',
  'auth.unknownError': 'একটি অজানা ত্রুটি ঘটেছে।',
  'auth.or': 'অথবা',
  'auth.noAccount': 'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
  'auth.haveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',

  // Home / Medicine List
  'home.title': 'আমার ঔষধ',
  'home.addMedicine': 'নতুন ঔষধ যোগ করুন',
  'home.noMedicines': 'এখনও কোন ঔষধ যোগ করা হয়নি। যোগ করতে + টিপুন!',
  'home.confirmDeleteTitle': 'ঔষধ মুছুন',
  'home.confirmDeleteContent':
      'আপনি কি নিশ্চিত যে আপনি {medicineName} মুছতে চান?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'ঔষধ যোগ করুন',
  'addMedicine.titleEdit': 'ঔষধ সম্পাদনা করুন',
  'addMedicine.nameLabel': 'ঔষধের নাম',
  'addMedicine.nameHint': 'যেমন, প্যারাসিটামল',
  'addMedicine.typeLabel': 'ঔষধের ধরন/বিভাগ',
  'addMedicine.typeHint': 'যেমন, ট্যাবলেট, সিরাপ, ইনজেকশন',
  'addMedicine.dosageLabel': 'ডোজের পরিমাণ',
  'addMedicine.dosageHint': 'যেমন, 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'ডোজের একক',
  'addMedicine.dosageUnitHint': 'যেমন, ট্যাবলেট, মিলি, মিলিগ্রাম',
  'addMedicine.frequencyLabel': 'ফ্রিকোয়েন্সি',
  'addMedicine.frequencyHint': 'যেমন, দৈনিক, দিনে দুবার',
  'addMedicine.durationLabel': 'সময়কাল (দিন)',
  'addMedicine.durationHint': 'যেমন, 7, 14, 30 (চলমান থাকার জন্য 0)',
  'addMedicine.whenToTakeLabel': 'কখন নেবেন / নোট',
  'addMedicine.whenToTakeHint': 'যেমন, খাবারের সাথে, ঘুমানোর আগে',
  'addMedicine.startDateLabel': 'শুরুর তারিখ',
  'addMedicine.endDateLabel': 'শেষ তারিখ (ঐচ্ছিক)',
  'addMedicine.selectDate': 'তারিখ নির্বাচন করুন',
  'addMedicine.selectTime': 'সময় নির্বাচন করুন',
  'addMedicine.timesLabel': 'দিনে কতবার',
  'addMedicine.addTime': 'সময় যোগ করুন',
  'addMedicine.notesLabel': 'অতিরিক্ত নোট (ঐচ্ছিক)',
  'addMedicine.notesHint': 'যেমন, ঠাণ্ডা জায়গায় রাখুন',
  'addMedicine.enableNotificationsLabel': 'ডোজ রিমাইন্ডার সক্রিয় করুন',
  'addMedicine.errorNumeric': 'অনুগ্রহ করে একটি বৈধ সংখ্যা লিখুন',
  'addMedicine.addMedicine': 'ঔষধ যোগ করুন',
  'addMedicine.save': 'সংরক্ষণ করুন',
  'addMedicine.name': 'ঔষধের নাম',
  'addMedicine.addMedicineHint': 'ঔষধের নাম (যেমন, প্যারাসিটামল)',
  'addMedicine.dosage': 'ডোজ',
  'addMedicine.dosageHint2': 'পরিমাণ (যেমন, 500)',
  'addMedicine.dosageUnit': 'একক (যেমন, মিলিগ্রাম)',
  'addMedicine.category': 'বিভাগ',
  'addMedicine.frequency': 'ফ্রিকোয়েন্সি ও সময়কাল',
  'addMedicine.selectDoseTimes': 'ডোজের সময় নির্বাচন করুন',
  'addMedicine.times': 'বার নির্বাচিত',
  'addMedicine.selectDuration': 'সময়কাল নির্বাচন করুন',
  'addMedicine.days': 'দিন',
  'addMedicine.whenToTake': 'কখন নেবেন',
  'addMedicine.beforeFood': 'খাবারের আগে',
  'addMedicine.afterFood': 'খাবারের পরে',
  'addMedicine.notifications': 'বিজ্ঞপ্তি',
  'addMedicine.enableNotifications': 'ডোজ রিমাইন্ডার সক্রিয় করুন',
  'addMedicine.receiveNotification': 'প্রতিটি ডোজের 5 মিনিট আগে বিজ্ঞপ্তি পান',
  'addMedicine.doseTimesPickerTitle': 'ডোজের সময় নির্বাচন করুন',
  'addMedicine.done': 'সম্পন্ন',

  // Medicine Controller Messages
  'medicine.addSuccess': 'ঔষধ সফলভাবে যোগ করা হয়েছে।',
  'medicine.updateSuccess': 'ঔষধ সফলভাবে আপডেট করা হয়েছে।',
  'medicine.deleteSuccess': 'ঔষধ সফলভাবে মুছে ফেলা হয়েছে।',
  'medicine.errorNeedTime': 'অনুগ্রহ করে কমপক্ষে একটি সময় নির্বাচন করুন।',
  'medicine.saveMedicineSuccess': 'ঔষধ সফলভাবে সংরক্ষণ করা হয়েছে।',
  'medicine.saveMedicineError': 'ত্রুটি',
  'medicine.saveMedicineErrorMessage': 'ঔষধ সংরক্ষণ করতে ব্যর্থ: {e}',
  'medicine.updateMedicineSuccess': 'ঔষধ সফলভাবে আপডেট করা হয়েছে।',
  'medicine.updateMedicineError': 'ত্রুটি',
  'medicine.updateMedicineErrorMessage': 'ঔষধ আপডেট করতে ব্যর্থ: {e}',
  'medicine.deleteMedicineSuccess': 'ঔষধ সফলভাবে মুছে ফেলা হয়েছে।',
  'medicine.deleteMedicineError': 'ত্রুটি',
  'medicine.deleteMedicineErrorMessage': 'ঔষধ মুছতে ব্যর্থ: {e}',
  'medicine.withFood': 'খাবারের সাথে',
  'medicine.deleteMedicineSuccessMessage': 'ঔষধ সফলভাবে মুছে ফেলা হয়েছে।',
  'medicine.saveMedicineSuccessMessage': 'ঔষধ সফলভাবে সংরক্ষিত হয়েছে।',

  // Settings Page
  'settings.title': 'সেটিংস',
  'settings.language': 'ভাষা',
  'settings.selectLanguage': 'ভাষা নির্বাচন করুন',
  'settings.profile': 'প্রোফাইল',

  // Introduction Screen
  'introduction.skip': 'এড়িয়ে যান',
  'introduction.done': 'সম্পন্ন',
  'introduction.next': 'পরবর্তী',

  // Filter
  'filter.allTypes': 'সকল ধরন',
  'filter.uncategorized': 'বিভাগহীন',
  'filter.searchHint': 'ঔষধ অনুসন্ধান করুন...',
  'filter.noResultsForSearchAndType':
      '\"{query}\" এর জন্য {type} ধরনে কোন ফলাফল নেই',
  'filter.noResultsForSearch': '\"{query}\" এর জন্য কোন ফলাফল নেই',
  'filter.noResultsForType': '\"{type}\" ধরনের জন্য কোন ফলাফল নেই',

  // Medicine Card
  'card.treatmentCompleted': 'চিকিৎসা সম্পন্ন হয়েছে',
  'card.nextDoseN_A': 'পরবর্তী ডোজ: প্রযোজ্য নয়',
  'card.todayAt': 'আজ',
  'card.tomorrowAt': 'আগামীকাল',
  'card.at': 'বাজে',
  'card.nextDose': 'পরবর্তী ডোজ:',
  'card.frequency.onceDaily': 'দিনে একবার',
  'card.frequency.twiceDaily': 'দিনে দুবার',
  'card.frequency.thriceDaily': 'দিনে তিনবার',
  'card.frequency.timesDaily': 'দিনে {count} বার',
  'addMedicine.nameLabelText': 'নাম',
  'addMedicine.dosageLabelText': 'ডোজ',
  'addMedicine.dosageQuantityHint': 'পরিমাণ (যেমন, 500)',
  'addMedicine.categoryLabel': 'বিভাগ',
  'addMedicine.frequencyDurationLabel': 'ফ্রিকোয়েন্সি ও সময়কাল',
  'addMedicine.selectDoseTimesPlaceholder': 'ডোজের সময় নির্বাচন করুন',
  'addMedicine.doseTimesBottomSheetTitle': 'ডোজের সময় নির্বাচন করুন',
  'addMedicine.timesSelectedInfo': '{count} বার নির্বাচিত',
  'addMedicine.selectDurationPlaceholder': 'সময়কাল নির্বাচন করুন',
  'addMedicine.durationSelectedInfo': '{count} দিন',
  'addMedicine.whenToTakeLabelText': 'কখন নেবেন',
  'addMedicine.beforeFoodOption': 'খাবারের আগে',
  'addMedicine.afterFoodOption': 'খাবারের পরে',
  'addMedicine.notificationsSectionLabel': 'বিজ্ঞপ্তি',
  'addMedicine.notificationSubtext': 'প্রতিটি ডোজের 5 মিনিট আগে বিজ্ঞপ্তি পান',
  'addMedicine.durationPickerTitle': 'সময়কাল নির্বাচন করুন (দিনে)',
  'addMedicine.durationPickerItemText': '{days} দিন',
  'addMedicine.timesSelected': 'বার নির্বাচিত',
  'addMedicine.notificationsLabel': 'বিজ্ঞপ্তি',
  'addMedicine.enableDoseReminders': 'ডোজ রিমাইন্ডার সক্রিয় করুন',
  'addMedicine.remindersSubtext': 'প্রতিটি ডোজের 5 মিনিট আগে বিজ্ঞপ্তি পান',

  // Profile Page
  'personal_info': 'ব্যক্তিগত তথ্য',
  'preferences': 'পছন্দসমূহ',
  'about_app': 'অ্যাপ সম্পর্কে',
  'app_version': 'অ্যাপ সংস্করণ',
  'privacy_policy': 'গোপনীয়তা নীতি',
  'developer': 'ডেভেলপার: ফুরকান আকিফ ইসলেক',
  'noEmail': 'কোন ইমেল পাওয়া যায়নি',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'অ্যাকাউন্ট মুছুন',
  'profile.deleteAccountImportantText':
      'আপনি কি নিশ্চিত যে আপনি আপনার অ্যাকাউন্ট মুছতে চান? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
  'profile.cancel': 'বাতিল করুন',
  'profile.delete': 'মুছুন',
  'profile.errorDeletingAccount': 'অ্যাকাউন্ট মুছতে ত্রুটি',
  'profile.deleteAccountButton': 'অ্যাকাউন্ট মুছুন',

  // Profile Page
  'logout': 'লগ আউট',
  'account': 'অ্যাকাউন্ট',

  // Blog Page
  'Blog': 'ব্লগ',
  'Bir hata oluştu.': 'একটি ত্রুটি ঘটেছে।',
  'Blog yazısı bulunamadı.': 'কোন ব্লগ পোস্ট পাওয়া যায়নি।',
  'Şuan blog yok': 'কোন ব্লগ উপলব্ধ নেই',
  'pills': 'বড়ি',
  'health': 'স্বাস্থ্য',
  'lifeStyle': 'জীবনযাপন',

  // Privacy Policy
  'privacy_policy_content':
      '<h3>ঔষধ রিমাইন্ডার - গোপনীয়তা নীতি</h3><br><p><b>ব্যক্তিগত তথ্যের ব্যবহার:</b><br>আমাদের অ্যাপ্লিকেশন আমাদের ব্যবহারকারীদের গোপনীয়তা রক্ষা করতে প্রতিশ্রুতিবদ্ধ। আমাদের ঔষধ রিমাইন্ডার অ্যাপে, আমরা ঔষধ ট্র্যাকিং এবং রিমাইন্ডারের জন্য প্রয়োজনীয় তথ্য (ইমেল, প্রোফাইল তথ্য এবং ঔষধ পরিকল্পনা) সংগ্রহ করি। এই তথ্য আমাদের পরিষেবা প্রদান ও উন্নত করতে ব্যবহার করা হয় এবং তৃতীয় পক্ষের সাথে শেয়ার করা হয় না।</p><br><p><b>ডাটা সংরক্ষণ এবং নিরাপত্তা:</b><br>আপনার ব্যবহারকারী ডাটা এনক্রিপ্টেড ফরম্যাটে নিরাপদ সার্ভারে সংরক্ষিত আছে। আপনার ঔষধ তথ্য এবং ব্যক্তিগত ডাটা শক্তিশালী নিরাপত্তা ব্যবস্থার অধীনে সুরক্ষিত। শুধুমাত্র প্রয়োজনীয় কর্মীরাই আপনার ডাটা অ্যাক্সেস করতে পারেন।</p><br><p><b>ব্যবহারকারীর অধিকার:</b><br>ব্যবহারকারীরা যে কোনো সময় তাদের অ্যাকাউন্ট এবং ডাটা দেখতে, সম্পাদনা করতে বা মুছতে পারেন। যখন আপনি আপনার অ্যাকাউন্ট মুছে ফেলেন, তখন আপনার সমস্ত ডাটা আমাদের সিস্টেম থেকে স্থায়ীভাবে সরিয়ে ফেলা হয়।</p><br><p><b>কুকিজ এবং ট্র্যাকিং:</b><br>আমাদের অ্যাপ্লিকেশন ব্যবহারকারী অভিজ্ঞতা উন্নত করতে কুকিজ ব্যবহার করতে পারে। এই কুকিজগুলি ব্যবহারকারীর পছন্দ এবং অ্যাপ্লিকেশন ব্যবহারের ডাটা সংরক্ষণ করে। আপনি চাইলে আপনার ব্রাউজার সেটিংস থেকে কুকিজ অক্ষম করতে পারেন।</p><br><p><b>বিজ্ঞপ্তি:</b><br>আমাদের অ্যাপ্লিকেশন শুধুমাত্র ব্যবহারকারী দ্বারা অনুমোদিত ঔষধ রিমাইন্ডারের জন্য বিজ্ঞপ্তি পাঠায়। আপনি অবাঞ্ছিত বিজ্ঞপ্তি পাবেন না এবং সেটিংস বিভাগ থেকে বিজ্ঞপ্তি অক্ষম করতে পারেন।</p><br><p><b>পরিবর্তন:</b><br>আমাদের গোপনীয়তা নীতি সময়ে সময়ে আপডেট করা হতে পারে। যখন উল্লেখযোগ্য পরিবর্তন হয়, তখন ব্যবহারকারীদের অবহিত করা হবে। আমাদের অ্যাপ্লিকেশন ব্যবহার করে, আপনি এই শর্তাবলীতে সম্মত হন।</p><br><p><b>যোগাযোগ:</b><br>আমাদের গোপনীয়তা নীতি সম্পর্কে কোনো প্রশ্ন থাকলে অনুগ্রহ করে আমাদের সাথে যোগাযোগ করুন।</p>',
};
