// lib/utils/localization/es_es.dart

const Map<String, String> esES = {
  // General
  'general.appTitle': 'Recordatorio de Medicamentos',
  'general.save': 'Guardar',
  'general.cancel': 'Cancelar',
  'general.delete': 'Eliminar',
  'general.edit': 'Editar',
  'general.add': 'Añadir',
  'general.confirm': 'Confirmar',
  'general.success': 'Éxito',
  'general.error': 'Error',
  'general.loading': 'Cargando...',
  'general.requiredField': 'Este campo es obligatorio',

  // Auth
  'auth.login': 'Iniciar Sesión',
  'auth.signup': 'Registrarse',
  'auth.logout': 'Cerrar Sesión',
  'auth.email': 'Correo electrónico',
  'auth.password': 'Contraseña',
  'auth.loginButton': 'Iniciar Sesión',
  'auth.signupButton': 'Registrarse',
  'auth.loginErrorTitle': 'Error de inicio de sesión',
  'auth.signupErrorTitle': 'Error de registro',
  'auth.unknownError': 'Ha ocurrido un error desconocido.',
  'auth.or': 'O',
  'auth.noAccount': '¿No tienes cuenta? Regístrate',
  'auth.haveAccount': '¿Ya tienes cuenta? Inicia sesión',

  // Home / Medicine List
  'home.title': 'Mis Medicamentos',
  'home.addMedicine': 'Añadir Nuevo Medicamento',
  'home.noMedicines':
      'Aún no hay medicamentos añadidos. ¡Pulsa + para añadir uno!',
  'home.confirmDeleteTitle': 'Eliminar Medicamento',
  'home.confirmDeleteContent':
      '¿Estás seguro de que quieres eliminar {medicineName}?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'Añadir Medicamento',
  'addMedicine.titleEdit': 'Editar Medicamento',
  'addMedicine.nameLabel': 'Nombre del Medicamento',
  'addMedicine.nameHint': 'ej. Paracetamol',
  'addMedicine.typeLabel': 'Tipo/Categoría del Medicamento',
  'addMedicine.typeHint': 'ej. Píldora, Jarabe, Inyección',
  'addMedicine.dosageLabel': 'Cantidad de Dosis',
  'addMedicine.dosageHint': 'ej. 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'Unidad de Dosis',
  'addMedicine.dosageUnitHint': 'ej. comprimido, mL, mg',
  'addMedicine.frequencyLabel': 'Frecuencia',
  'addMedicine.frequencyHint': 'ej. Diario, Dos veces al día',
  'addMedicine.durationLabel': 'Duración (días)',
  'addMedicine.durationHint': 'ej. 7, 14, 30 (0 para continuo)',
  'addMedicine.whenToTakeLabel': 'Cuándo Tomar / Notas',
  'addMedicine.whenToTakeHint': 'ej. Con comida, Antes de dormir',
  'addMedicine.startDateLabel': 'Fecha de Inicio',
  'addMedicine.endDateLabel': 'Fecha de Fin (Opcional)',
  'addMedicine.selectDate': 'Seleccionar Fecha',
  'addMedicine.selectTime': 'Seleccionar Hora',
  'addMedicine.timesLabel': 'Veces al Día',
  'addMedicine.addTime': 'Añadir Hora',
  'addMedicine.notesLabel': 'Notas Adicionales (Opcional)',
  'addMedicine.notesHint': 'ej. Guardar en lugar fresco',
  'addMedicine.enableNotificationsLabel': 'Activar Recordatorios de Dosis',
  'addMedicine.errorNumeric': 'Por favor, introduce un número válido',
  'addMedicine.addMedicine': 'Añadir Medicamento',
  'addMedicine.save': 'Guardar',
  'addMedicine.name': 'Nombre del Medicamento',
  'addMedicine.addMedicineHint': 'Nombre del Medicamento (ej. Paracetamol)',
  'addMedicine.dosage': 'Dosis',
  'addMedicine.dosageHint2': 'Cantidad (ej. 500)',
  'addMedicine.dosageUnit': 'Unidad (ej. mg)',
  'addMedicine.category': 'Categoría',
  'addMedicine.frequency': 'Frecuencia & Duración',
  'addMedicine.selectDoseTimes': 'Seleccionar Horas de Dosis',
  'addMedicine.times': 'vez/veces seleccionada(s)',
  'addMedicine.selectDuration': 'Seleccionar Duración',
  'addMedicine.days': 'día(s)',
  'addMedicine.whenToTake': 'Cuándo Tomar',
  'addMedicine.beforeFood': 'Antes de Comer',
  'addMedicine.afterFood': 'Después de Comer',
  'addMedicine.notifications': 'Notificaciones',
  'addMedicine.enableNotifications': 'Activar Recordatorios de Dosis',
  'addMedicine.receiveNotification':
      'Recibir una notificación 5 minutos antes de cada dosis',
  'addMedicine.doseTimesPickerTitle': 'Seleccionar Horas de Dosis',
  'addMedicine.done': 'Hecho',

  // Medicine Controller Messages
  'medicine.addSuccess': 'Medicamento añadido correctamente.',
  'medicine.updateSuccess': 'Medicamento actualizado correctamente.',
  'medicine.deleteSuccess': 'Medicamento eliminado correctamente.',
  'medicine.errorNeedTime': 'Por favor, selecciona al menos una hora.',
  'medicine.saveMedicineSuccess': 'Medicamento guardado correctamente.',
  'medicine.saveMedicineError': 'Error',
  'medicine.saveMedicineErrorMessage': 'Error al guardar el medicamento: {e}',
  'medicine.updateMedicineSuccess': 'Medicamento actualizado correctamente.',
  'medicine.updateMedicineError': 'Error',
  'medicine.updateMedicineErrorMessage':
      'Error al actualizar el medicamento: {e}',
  'medicine.deleteMedicineSuccess': 'Medicamento eliminado correctamente.',
  'medicine.deleteMedicineError': 'Error',
  'medicine.deleteMedicineErrorMessage':
      'Error al eliminar el medicamento: {e}',
  'medicine.withFood': 'Con Comida',
  'medicine.deleteMedicineSuccessMessage':
      'Medicamento eliminado correctamente.',

  // Settings Page
  'settings.title': 'Ajustes',
  'settings.language': 'Idioma',
  'settings.selectLanguage': 'Seleccionar Idioma',
  'settings.profile': 'Perfil',

  // Introduction Screen
  'introduction.skip': 'Omitir',
  'introduction.done': 'Hecho',
  'introduction.next': 'Siguiente',

  // Filter
  'filter.allTypes': 'Todos los Tipos',
  'filter.uncategorized': 'Sin Categoría',
  'filter.searchHint': 'Buscar Medicamentos...',
  'filter.noResultsForSearchAndType':
      'No hay resultados para \"{query}\" en {type}',
  'filter.noResultsForSearch': 'No hay resultados para \"{query}\"',
  'filter.noResultsForType': 'No hay resultados para el tipo \"{type}\"',

  // Medicine Card
  'card.treatmentCompleted': 'Tratamiento Completado',
  'card.nextDoseN_A': 'Próxima dosis: N/A',
  'card.todayAt': 'Hoy a las',
  'card.tomorrowAt': 'Mañana a las',
  'card.at': 'a las',
  'card.nextDose': 'Próxima dosis:',
  'card.frequency.onceDaily': 'Una vez al día',
  'card.frequency.twiceDaily': 'Dos veces al día',
  'card.frequency.thriceDaily': 'Tres veces al día',
  'card.frequency.timesDaily': '{count} veces al día',
  'addMedicine.nameLabelText': 'Nombre',
  'addMedicine.dosageLabelText': 'Dosis',
  'addMedicine.dosageQuantityHint': 'Cantidad (ej. 500)',
  'addMedicine.categoryLabel': 'Categoría',
  'addMedicine.frequencyDurationLabel': 'Frecuencia & Duración',
  'addMedicine.selectDoseTimesPlaceholder': 'Seleccionar Horas de Dosis',
  'addMedicine.doseTimesBottomSheetTitle': 'Seleccionar Horas de Dosis',
  'addMedicine.timesSelectedInfo': '{count} hora(s) seleccionada(s)',
  'addMedicine.selectDurationPlaceholder': 'Seleccionar Duración',
  'addMedicine.durationSelectedInfo': '{count} día(s)',
  'addMedicine.whenToTakeLabelText': 'Cuándo Tomar',
  'addMedicine.beforeFoodOption': 'Antes de Comer',
  'addMedicine.afterFoodOption': 'Después de Comer',
  'addMedicine.notificationsSectionLabel': 'Notificaciones',
  'addMedicine.notificationSubtext':
      'Recibir una notificación 5 minutos antes de cada dosis',
  'addMedicine.durationPickerTitle': 'Seleccionar Duración (en días)',
  'addMedicine.durationPickerItemText': '{days} día(s)',
  'addMedicine.timesSelected': 'veces seleccionadas',
  'addMedicine.notificationsLabel': 'Notificaciones',
  'addMedicine.enableDoseReminders': 'Activar Recordatorios de Dosis',
  'addMedicine.remindersSubtext':
      'Recibir una notificación 5 minutos antes de cada dosis',

  // Profile Page
  'personal_info': 'Información Personal',
  'preferences': 'Preferencias',
  'about_app': 'Acerca de la Aplicación',
  'app_version': 'Versión de la Aplicación',
  'privacy_policy': 'Política de Privacidad',
  'developer': 'Desarrollador: Furkan Akif İŞLEK',
  'noEmail': 'No se encontró correo electrónico',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'Eliminar Cuenta',
  'profile.deleteAccountImportantText':
      '¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.',
  'profile.cancel': 'Cancelar',
  'profile.delete': 'Eliminar',
  'profile.errorDeletingAccount': 'Error al eliminar la cuenta',
  'profile.deleteAccountButton': 'Eliminar Cuenta',

  // Profile Page
  'logout': 'Cerrar Sesión',
  'account': 'Cuenta',
};
