// lib/utils/localization/hi_in.dart

const Map<String, String> hiIN = {
  // General
  'general.appTitle': 'दवा रिमाइंडर',
  'general.save': 'सहेजें',
  'general.cancel': 'रद्द करें',
  'general.delete': 'हटाएं',
  'general.edit': 'संपादित करें',
  'general.add': 'जोड़ें',
  'general.confirm': 'पुष्टि करें',
  'general.success': 'सफलता',
  'general.error': 'त्रुटि',
  'general.loading': 'लोड हो रहा है...',
  'general.requiredField': 'यह फ़ील्ड आवश्यक है',
  'general.done': 'पूर्ण',

  // Auth
  'auth.login': 'लॉगिन',
  'auth.signup': 'साइन अप',
  'auth.logout': 'लॉगआउट',
  'auth.email': 'ईमेल',
  'auth.password': 'पासवर्ड',
  'auth.loginButton': 'लॉगिन करें',
  'auth.signupButton': 'साइन अप करें',
  'auth.loginErrorTitle': 'लॉगिन विफल',
  'auth.signupErrorTitle': 'साइन अप विफल',
  'auth.unknownError': 'एक अज्ञात त्रुटि हुई।',
  'auth.or': 'या',
  'auth.noAccount': 'खाता नहीं है? साइन अप करें',
  'auth.haveAccount': 'पहले से ही खाता है? लॉगिन करें',

  // Home / Medicine List
  'home.title': 'मेरी दवाइयां',
  'home.addMedicine': 'नई दवा जोड़ें',
  'home.noMedicines':
      'अभी तक कोई दवा नहीं जोड़ी गई। एक जोड़ने के लिए + पर टैप करें!',
  'home.confirmDeleteTitle': 'दवा हटाएं',
  'home.confirmDeleteContent':
      'क्या आप वाकई {medicineName} को हटाना चाहते हैं?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'दवा जोड़ें',
  'addMedicine.titleEdit': 'दवा संपादित करें',
  'addMedicine.nameLabel': 'दवा का नाम',
  'addMedicine.nameHint': 'उदा. पैरासिटामोल',
  'addMedicine.typeLabel': 'दवा का प्रकार/श्रेणी',
  'addMedicine.typeHint': 'उदा. गोली, सिरप, इंजेक्शन',
  'addMedicine.dosageLabel': 'खुराक मात्रा',
  'addMedicine.dosageHint': 'उदा. 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'खुराक इकाई',
  'addMedicine.dosageUnitHint': 'उदा. टैबलेट, मिलीलीटर, मिलीग्राम',
  'addMedicine.frequencyLabel': 'आवृत्ति',
  'addMedicine.frequencyHint': 'उदा. दैनिक, दिन में दो बार',
  'addMedicine.durationLabel': 'अवधि (दिन)',
  'addMedicine.durationHint': 'उदा. 7, 14, 30 (निरंतर के लिए 0)',
  'addMedicine.whenToTakeLabel': 'कब लेना है / नोट्स',
  'addMedicine.whenToTakeHint': 'उदा. भोजन के साथ, सोने से पहले',
  'addMedicine.startDateLabel': 'आरंभ तिथि',
  'addMedicine.endDateLabel': 'समाप्ति तिथि (वैकल्पिक)',
  'addMedicine.selectDate': 'तिथि चुनें',
  'addMedicine.selectTime': 'समय चुनें',
  'addMedicine.timesLabel': 'प्रति दिन बार',
  'addMedicine.addTime': 'समय जोड़ें',
  'addMedicine.notesLabel': 'अतिरिक्त नोट्स (वैकल्पिक)',
  'addMedicine.notesHint': 'उदा. ठंडी जगह पर रखें',
  'addMedicine.enableNotificationsLabel': 'खुराक अनुस्मारक सक्षम करें',
  'addMedicine.errorNumeric': 'कृपया एक वैध संख्या दर्ज करें',
  'addMedicine.addMedicine': 'दवा जोड़ें',
  'addMedicine.save': 'सहेजें',
  'addMedicine.name': 'दवा का नाम',
  'addMedicine.addMedicineHint': 'दवा का नाम (उदा. पैरासिटामोल)',
  'addMedicine.dosage': 'खुराक',
  'addMedicine.dosageHint2': 'मात्रा (उदा. 500)',
  'addMedicine.dosageUnit': 'इकाई (उदा. मिलीग्राम)',
  'addMedicine.category': 'श्रेणी',
  'addMedicine.frequency': 'आवृत्ति और अवधि',
  'addMedicine.selectDoseTimes': 'खुराक समय चुनें',
  'addMedicine.times': 'बार चयनित',
  'addMedicine.selectDuration': 'अवधि चुनें',
  'addMedicine.days': 'दिन',
  'addMedicine.whenToTake': 'कब लेना है',
  'addMedicine.beforeFood': 'भोजन से पहले',
  'addMedicine.afterFood': 'भोजन के बाद',
  'addMedicine.notifications': 'सूचनाएँ',
  'addMedicine.enableNotifications': 'खुराक अनुस्मारक सक्षम करें',
  'addMedicine.receiveNotification':
      'प्रत्येक खुराक से 5 मिनट पहले एक सूचना प्राप्त करें',
  'addMedicine.doseTimesPickerTitle': 'खुराक समय चुनें',
  'addMedicine.done': 'पूर्ण',

  // Medicine Controller Messages
  'medicine.addSuccess': 'दवा सफलतापूर्वक जोड़ी गई।',
  'medicine.updateSuccess': 'दवा सफलतापूर्वक अपडेट की गई।',
  'medicine.deleteSuccess': 'दवा सफलतापूर्वक हटा दी गई।',
  'medicine.errorNeedTime': 'कृपया कम से कम एक समय चुनें।',
  'medicine.saveMedicineSuccess': 'दवा सफलतापूर्वक सहेजी गई।',
  'medicine.saveMedicineError': 'त्रुटि',
  'medicine.saveMedicineErrorMessage': 'दवा सहेजने में विफल: {e}',
  'medicine.updateMedicineSuccess': 'दवा सफलतापूर्वक अपडेट की गई।',
  'medicine.updateMedicineError': 'त्रुटि',
  'medicine.updateMedicineErrorMessage': 'दवा अपडेट करने में विफल: {e}',
  'medicine.deleteMedicineSuccess': 'दवा सफलतापूर्वक हटा दी गई।',
  'medicine.deleteMedicineError': 'त्रुटि',
  'medicine.deleteMedicineErrorMessage': 'दवा हटाने में विफल: {e}',
  'medicine.withFood': 'भोजन के साथ',
  'medicine.deleteMedicineSuccessMessage': 'दवा सफलतापूर्वक हटा दी गई।',

  // Settings Page
  'settings.title': 'सेटिंग्स',
  'settings.language': 'भाषा',
  'settings.selectLanguage': 'भाषा चुनें',
  'settings.profile': 'प्रोफ़ाइल',

  // Introduction Screen
  'introduction.skip': 'छोड़ें',
  'introduction.done': 'पूर्ण',
  'introduction.next': 'अगला',

  // Filter
  'filter.allTypes': 'सभी प्रकार',
  'filter.uncategorized': 'अवर्गीकृत',
  'filter.searchHint': 'दवाइयां खोजें...',
  'filter.noResultsForSearchAndType':
      '{type} में \"{query}\" के लिए कोई परिणाम नहीं',
  'filter.noResultsForSearch': '\"{query}\" के लिए कोई परिणाम नहीं',
  'filter.noResultsForType': 'प्रकार \"{type}\" के लिए कोई परिणाम नहीं',

  // Medicine Card
  'card.treatmentCompleted': 'उपचार पूरा हुआ',
  'card.nextDoseN_A': 'अगली खुराक: N/A',
  'card.todayAt': 'आज',
  'card.tomorrowAt': 'कल',
  'card.at': 'बजे',
  'card.nextDose': 'अगली खुराक:',
  'card.frequency.onceDaily': 'दिन में एक बार',
  'card.frequency.twiceDaily': 'दिन में दो बार',
  'card.frequency.thriceDaily': 'दिन में तीन बार',
  'card.frequency.timesDaily': 'दिन में {count} बार',
  'addMedicine.nameLabelText': 'नाम',
  'addMedicine.dosageLabelText': 'खुराक',
  'addMedicine.dosageQuantityHint': 'मात्रा (उदा. 500)',
  'addMedicine.categoryLabel': 'श्रेणी',
  'addMedicine.frequencyDurationLabel': 'आवृत्ति और अवधि',
  'addMedicine.selectDoseTimesPlaceholder': 'खुराक समय चुनें',
  'addMedicine.doseTimesBottomSheetTitle': 'खुराक समय चुनें',
  'addMedicine.timesSelectedInfo': '{count} समय चयनित',
  'addMedicine.selectDurationPlaceholder': 'अवधि चुनें',
  'addMedicine.durationSelectedInfo': '{count} दिन',
  'addMedicine.whenToTakeLabelText': 'कब लेना है',
  'addMedicine.beforeFoodOption': 'भोजन से पहले',
  'addMedicine.afterFoodOption': 'भोजन के बाद',
  'addMedicine.notificationsSectionLabel': 'सूचनाएँ',
  'addMedicine.notificationSubtext':
      'प्रत्येक खुराक से 5 मिनट पहले एक सूचना प्राप्त करें',
  'addMedicine.durationPickerTitle': 'अवधि चुनें (दिनों में)',
  'addMedicine.durationPickerItemText': '{days} दिन',
  'addMedicine.timesSelected': 'बार चयनित',
  'addMedicine.notificationsLabel': 'सूचनाएँ',
  'addMedicine.enableDoseReminders': 'खुराक अनुस्मारक सक्षम करें',
  'addMedicine.remindersSubtext':
      'प्रत्येक खुराक से 5 मिनट पहले एक सूचना प्राप्त करें',

  // Profile Page
  'personal_info': 'व्यक्तिगत जानकारी',
  'preferences': 'प्राथमिकताएँ',
  'about_app': 'ऐप के बारे में',
  'app_version': 'ऐप संस्करण',
  'privacy_policy': 'गोपनीयता नीति',
  'developer': 'डेवलपर: Furkan Akif İŞLEK',
  'noEmail': 'कोई ईमेल नहीं मिला',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'खाता हटाएं',
  'profile.deleteAccountImportantText':
      'क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
  'profile.cancel': 'रद्द करें',
  'profile.delete': 'हटाएं',
  'profile.errorDeletingAccount': 'खाता हटाने में त्रुटि',
  'profile.deleteAccountButton': 'खाता हटाएं',

  // Profile Page
  'logout': 'लॉगआउट',
  'account': 'खाता',
};
