// lib/utils/localization/id_id.dart

const Map<String, String> idID = {
  // General
  'general.appTitle': 'Pengingat Obat',
  'general.save': 'Simpan',
  'general.cancel': 'Batal',
  'general.delete': 'Hapus',
  'general.edit': 'Edit',
  'general.add': 'Tambah',
  'general.confirm': 'Konfirmasi',
  'general.success': 'Berhasil',
  'general.error': 'Kesalahan',
  'general.loading': 'Memuat...',
  'general.requiredField': 'Bidang ini wajib diisi',
  'general.done': 'Selesai',

  // Auth
  'auth.login': 'Masuk',
  'auth.signup': 'Daftar',
  'auth.logout': 'Keluar',
  'auth.email': 'Email',
  'auth.password': 'Kata Sandi',
  'auth.loginButton': 'Masuk',
  'auth.signupButton': 'Daftar',
  'auth.loginErrorTitle': 'Gagal Masuk',
  'auth.signupErrorTitle': 'Gagal Mendaftar',
  'auth.unknownError': 'Terjadi kesalahan yang tidak diketahui.',
  'auth.or': 'ATAU',
  'auth.noAccount': 'Belum punya akun? Daftar',
  'auth.haveAccount': 'Sudah punya akun? Masuk',

  // Home / Medicine List
  'home.title': 'Obat Saya',
  'home.addMedicine': 'Tambah Obat Baru',
  'home.noMedicines': 'Belum ada obat ditambahkan. Ketuk + untuk menambahkan!',
  'home.confirmDeleteTitle': 'Hapus Obat',
  'home.confirmDeleteContent':
      'Apakah Anda yakin ingin menghapus {medicineName}?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'Tambah Obat',
  'addMedicine.titleEdit': 'Edit Obat',
  'addMedicine.nameLabel': 'Nama Obat',
  'addMedicine.nameHint': 'mis. Paracetamol',
  'addMedicine.typeLabel': 'Jenis/Kategori Obat',
  'addMedicine.typeHint': 'mis. Pil, Sirup, Suntikan',
  'addMedicine.dosageLabel': 'Jumlah Dosis',
  'addMedicine.dosageHint': 'mis. 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'Unit Dosis',
  'addMedicine.dosageUnitHint': 'mis. tablet, mL, mg',
  'addMedicine.frequencyLabel': 'Frekuensi',
  'addMedicine.frequencyHint': 'mis. Harian, Dua kali sehari',
  'addMedicine.durationLabel': 'Durasi (hari)',
  'addMedicine.durationHint': 'mis. 7, 14, 30 (0 untuk berkelanjutan)',
  'addMedicine.whenToTakeLabel': 'Kapan Diminum / Catatan',
  'addMedicine.whenToTakeHint': 'mis. Dengan makanan, Sebelum tidur',
  'addMedicine.startDateLabel': 'Tanggal Mulai',
  'addMedicine.endDateLabel': 'Tanggal Selesai (Opsional)',
  'addMedicine.selectDate': 'Pilih Tanggal',
  'addMedicine.selectTime': 'Pilih Waktu',
  'addMedicine.timesLabel': 'Kali per Hari',
  'addMedicine.addTime': 'Tambah Waktu',
  'addMedicine.notesLabel': 'Catatan Tambahan (Opsional)',
  'addMedicine.notesHint': 'mis. Simpan di tempat sejuk',
  'addMedicine.enableNotificationsLabel': 'Aktifkan Pengingat Dosis',
  'addMedicine.errorNumeric': 'Harap masukkan angka yang valid',
  'addMedicine.addMedicine': 'Tambah Obat',
  'addMedicine.save': 'Simpan',
  'addMedicine.name': 'Nama Obat',
  'addMedicine.addMedicineHint': 'Nama Obat (mis. Paracetamol)',
  'addMedicine.dosage': 'Dosis',
  'addMedicine.dosageHint2': 'Jumlah (mis. 500)',
  'addMedicine.dosageUnit': 'Unit (mis. mg)',
  'addMedicine.category': 'Kategori',
  'addMedicine.frequency': 'Frekuensi & Durasi',
  'addMedicine.selectDoseTimes': 'Pilih Waktu Dosis',
  'addMedicine.times': 'kali dipilih',
  'addMedicine.selectDuration': 'Pilih Durasi',
  'addMedicine.days': 'hari',
  'addMedicine.whenToTake': 'Kapan Diminum',
  'addMedicine.beforeFood': 'Sebelum Makan',
  'addMedicine.afterFood': 'Setelah Makan',
  'addMedicine.notifications': 'Notifikasi',
  'addMedicine.enableNotifications': 'Aktifkan Pengingat Dosis',
  'addMedicine.receiveNotification':
      'Terima notifikasi 5 menit sebelum setiap dosis',
  'addMedicine.doseTimesPickerTitle': 'Pilih Waktu Dosis',
  'addMedicine.done': 'Selesai',

  // Medicine Controller Messages
  'medicine.addSuccess': 'Obat berhasil ditambahkan.',
  'medicine.updateSuccess': 'Obat berhasil diperbarui.',
  'medicine.deleteSuccess': 'Obat berhasil dihapus.',
  'medicine.errorNeedTime': 'Harap pilih setidaknya satu waktu.',
  'medicine.saveMedicineSuccess': 'Obat berhasil disimpan.',
  'medicine.saveMedicineError': 'Kesalahan',
  'medicine.saveMedicineErrorMessage': 'Gagal menyimpan obat: {e}',
  'medicine.updateMedicineSuccess': 'Obat berhasil diperbarui.',
  'medicine.updateMedicineError': 'Kesalahan',
  'medicine.updateMedicineErrorMessage': 'Gagal memperbarui obat: {e}',
  'medicine.deleteMedicineSuccess': 'Obat berhasil dihapus.',
  'medicine.deleteMedicineError': 'Kesalahan',
  'medicine.deleteMedicineErrorMessage': 'Gagal menghapus obat: {e}',
  'medicine.withFood': 'Dengan Makanan',
  'medicine.deleteMedicineSuccessMessage': 'Obat berhasil dihapus.',

  // Settings Page
  'settings.title': 'Pengaturan',
  'settings.language': 'Bahasa',
  'settings.selectLanguage': 'Pilih Bahasa',
  'settings.profile': 'Profil',

  // Introduction Screen
  'introduction.skip': 'Lewati',
  'introduction.done': 'Selesai',
  'introduction.next': 'Selanjutnya',

  // Filter
  'filter.allTypes': 'Semua Jenis',
  'filter.uncategorized': 'Tidak Berkategori',
  'filter.searchHint': 'Cari Obat...',
  'filter.noResultsForSearchAndType':
      'Tidak ada hasil untuk "{query}" di {type}',
  'filter.noResultsForSearch': 'Tidak ada hasil untuk "{query}"',
  'filter.noResultsForType': 'Tidak ada hasil untuk jenis "{type}"',

  // Medicine Card
  'card.treatmentCompleted': 'Pengobatan Selesai',
  'card.nextDoseN_A': 'Dosis berikutnya: N/A',
  'card.todayAt': 'Hari ini pukul',
  'card.tomorrowAt': 'Besok pukul',
  'card.at': 'pukul',
  'card.nextDose': 'Dosis berikutnya:',
  'card.frequency.onceDaily': 'Sekali sehari',
  'card.frequency.twiceDaily': 'Dua kali sehari',
  'card.frequency.thriceDaily': 'Tiga kali sehari',
  'card.frequency.timesDaily': '{count} kali sehari',
  'addMedicine.nameLabelText': 'Nama',
  'addMedicine.dosageLabelText': 'Dosis',
  'addMedicine.dosageQuantityHint': 'Jumlah (mis. 500)',
  'addMedicine.categoryLabel': 'Kategori',
  'addMedicine.frequencyDurationLabel': 'Frekuensi & Durasi',
  'addMedicine.selectDoseTimesPlaceholder': 'Pilih Waktu Dosis',
  'addMedicine.doseTimesBottomSheetTitle': 'Pilih Waktu Dosis',
  'addMedicine.timesSelectedInfo': '{count} waktu dipilih',
  'addMedicine.selectDurationPlaceholder': 'Pilih Durasi',
  'addMedicine.durationSelectedInfo': '{count} hari',
  'addMedicine.whenToTakeLabelText': 'Kapan Diminum',
  'addMedicine.beforeFoodOption': 'Sebelum Makan',
  'addMedicine.afterFoodOption': 'Setelah Makan',
  'addMedicine.notificationsSectionLabel': 'Notifikasi',
  'addMedicine.notificationSubtext':
      'Terima notifikasi 5 menit sebelum setiap dosis',
  'addMedicine.durationPickerTitle': 'Pilih Durasi (dalam hari)',
  'addMedicine.durationPickerItemText': '{days} hari',
  'addMedicine.timesSelected': 'kali dipilih',
  'addMedicine.notificationsLabel': 'Notifikasi',
  'addMedicine.enableDoseReminders': 'Aktifkan Pengingat Dosis',
  'addMedicine.remindersSubtext':
      'Terima notifikasi 5 menit sebelum setiap dosis',

  // Profile Page
  'personal_info': 'Informasi Pribadi',
  'preferences': 'Preferensi',
  'about_app': 'Tentang Aplikasi',
  'app_version': 'Versi Aplikasi',
  'privacy_policy': 'Kebijakan Privasi',
  'developer': 'Pengembang: Furkan Akif İŞLEK',
  'noEmail': 'Email tidak ditemukan',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'Hapus Akun',
  'profile.deleteAccountImportantText':
      'Apakah Anda yakin ingin menghapus akun Anda? Tindakan ini tidak dapat dibatalkan.',
  'profile.cancel': 'Batal',
  'profile.delete': 'Hapus',
  'profile.errorDeletingAccount': 'Kesalahan menghapus akun',
  'profile.deleteAccountButton': 'Hapus Akun',

  // Profile Page
  'logout': 'Keluar',
  'account': 'Akun',
};
