// lib/utils/localization/it_it.dart

const Map<String, String> itIT = {
  // General
  'general.appTitle': 'Promemoria Farmaci',
  'general.save': 'Salva',
  'general.cancel': 'Annulla',
  'general.delete': 'Elimina',
  'general.edit': 'Modifica',
  'general.add': 'Aggiungi',
  'general.confirm': 'Conferma',
  'general.success': 'Successo',
  'general.error': 'Errore',
  'general.loading': 'Caricamento...',
  'general.requiredField': 'Questo campo è obbligatorio',

  // Auth
  'auth.login': 'Accedi',
  'auth.signup': 'Registrati',
  'auth.logout': 'Esci',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.loginButton': 'Accedi',
  'auth.signupButton': 'Registrati',
  'auth.loginErrorTitle': 'Accesso fallito',
  'auth.signupErrorTitle': 'Registrazione fallita',
  'auth.unknownError': 'Si è verificato un errore sconosciuto.',
  'auth.or': 'OPPURE',
  'auth.noAccount': 'Non hai un account? Registrati',
  'auth.haveAccount': 'Hai già un account? Accedi',

  // Home / Medicine List
  'home.title': 'I miei farmaci',
  'home.addMedicine': 'Aggiungi nuovo farmaco',
  'home.noMedicines': 'Nessun farmaco aggiunto. Tocca + per aggiungerne uno!',
  'home.confirmDeleteTitle': 'Elimina farmaco',
  'home.confirmDeleteContent': 'Sei sicuro di voler eliminare {medicineName}?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'Aggiungi farmaco',
  'addMedicine.titleEdit': 'Modifica farmaco',
  'addMedicine.nameLabel': 'Nome farmaco',
  'addMedicine.nameHint': 'es. Paracetamolo',
  'addMedicine.typeLabel': 'Tipo/Categoria farmaco',
  'addMedicine.typeHint': 'es. Pillola, Sciroppo, Iniezione',
  'addMedicine.dosageLabel': 'Quantità dose',
  'addMedicine.dosageHint': 'es. 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'Unità dose',
  'addMedicine.dosageUnitHint': 'es. compressa, mL, mg',
  'addMedicine.frequencyLabel': 'Frequenza',
  'addMedicine.frequencyHint': 'es. Giornaliero, Due volte al giorno',
  'addMedicine.durationLabel': 'Durata (giorni)',
  'addMedicine.durationHint': 'es. 7, 14, 30 (0 per continuo)',
  'addMedicine.whenToTakeLabel': 'Quando assumere / Note',
  'addMedicine.whenToTakeHint': 'es. Con i pasti, Prima di dormire',
  'addMedicine.startDateLabel': 'Data inizio',
  'addMedicine.endDateLabel': 'Data fine (Opzionale)',
  'addMedicine.selectDate': 'Seleziona data',
  'addMedicine.selectTime': 'Seleziona ora',
  'addMedicine.timesLabel': 'Volte al giorno',
  'addMedicine.addTime': 'Aggiungi ora',
  'addMedicine.notesLabel': 'Note aggiuntive (Opzionale)',
  'addMedicine.notesHint': 'es. Conservare in luogo fresco',
  'addMedicine.enableNotificationsLabel': 'Attiva promemoria dosi',
  'addMedicine.errorNumeric': 'Inserisci un numero valido',
  'addMedicine.addMedicine': 'Aggiungi farmaco',
  'addMedicine.save': 'Salva',
  'addMedicine.name': 'Nome farmaco',
  'addMedicine.addMedicineHint': 'Nome farmaco (es. Paracetamolo)',
  'addMedicine.dosage': 'Dosaggio',
  'addMedicine.dosageHint2': 'Quantità (es. 500)',
  'addMedicine.dosageUnit': 'Unità (es. mg)',
  'addMedicine.category': 'Categoria',
  'addMedicine.frequency': 'Frequenza & Durata',
  'addMedicine.selectDoseTimes': 'Seleziona orari dose',
  'addMedicine.times': 'volte selezionate',
  'addMedicine.selectDuration': 'Seleziona durata',
  'addMedicine.days': 'giorni',
  'addMedicine.whenToTake': 'Quando assumere',
  'addMedicine.beforeFood': 'Prima dei pasti',
  'addMedicine.afterFood': 'Dopo i pasti',
  'addMedicine.notifications': 'Notifiche',
  'addMedicine.enableNotifications': 'Attiva promemoria dosi',
  'addMedicine.receiveNotification':
      'Ricevi una notifica 5 minuti prima di ogni dose',
  'addMedicine.doseTimesPickerTitle': 'Seleziona orari dose',
  'addMedicine.done': 'Fatto',

  // Medicine Controller Messages
  'medicine.addSuccess': 'Farmaco aggiunto con successo.',
  'medicine.updateSuccess': 'Farmaco aggiornato con successo.',
  'medicine.deleteSuccess': 'Farmaco eliminato con successo.',
  'medicine.errorNeedTime': 'Seleziona almeno un orario.',
  'medicine.saveMedicineSuccess': 'Farmaco salvato con successo.',
  'medicine.saveMedicineError': 'Errore',
  'medicine.saveMedicineErrorMessage': 'Errore nel salvare il farmaco: {e}',
  'medicine.updateMedicineSuccess': 'Farmaco aggiornato con successo.',
  'medicine.updateMedicineError': 'Errore',
  'medicine.updateMedicineErrorMessage':
      'Errore nell\'aggiornare il farmaco: {e}',
  'medicine.deleteMedicineSuccess': 'Farmaco eliminato con successo.',
  'medicine.deleteMedicineError': 'Errore',
  'medicine.deleteMedicineErrorMessage':
      'Errore nell\'eliminare il farmaco: {e}',
  'medicine.withFood': 'Con i pasti',
  'medicine.deleteMedicineSuccessMessage': 'Farmaco eliminato con successo.',

  // Settings Page
  'settings.title': 'Impostazioni',
  'settings.language': 'Lingua',
  'settings.selectLanguage': 'Seleziona lingua',
  'settings.profile': 'Profilo',

  // Introduction Screen
  'introduction.skip': 'Salta',
  'introduction.done': 'Fatto',
  'introduction.next': 'Avanti',

  // Filter
  'filter.allTypes': 'Tutti i tipi',
  'filter.uncategorized': 'Non categorizzato',
  'filter.searchHint': 'Cerca farmaci...',
  'filter.noResultsForSearchAndType':
      'Nessun risultato per \"{query}\" in {type}',
  'filter.noResultsForSearch': 'Nessun risultato per \"{query}\"',
  'filter.noResultsForType': 'Nessun risultato per il tipo \"{type}\"',

  // Medicine Card
  'card.treatmentCompleted': 'Trattamento completato',
  'card.nextDoseN_A': 'Prossima dose: N/D',
  'card.todayAt': 'Oggi alle',
  'card.tomorrowAt': 'Domani alle',
  'card.at': 'alle',
  'card.nextDose': 'Prossima dose:',
  'card.frequency.onceDaily': 'Una volta al giorno',
  'card.frequency.twiceDaily': 'Due volte al giorno',
  'card.frequency.thriceDaily': 'Tre volte al giorno',
  'card.frequency.timesDaily': '{count} volte al giorno',
  'addMedicine.nameLabelText': 'Nome',
  'addMedicine.dosageLabelText': 'Dosaggio',
  'addMedicine.dosageQuantityHint': 'Quantità (es. 500)',
  'addMedicine.categoryLabel': 'Categoria',
  'addMedicine.frequencyDurationLabel': 'Frequenza & Durata',
  'addMedicine.selectDoseTimesPlaceholder': 'Seleziona orari dose',
  'addMedicine.doseTimesBottomSheetTitle': 'Seleziona orari dose',
  'addMedicine.timesSelectedInfo': '{count} volte selezionate',
  'addMedicine.selectDurationPlaceholder': 'Seleziona durata',
  'addMedicine.durationSelectedInfo': '{count} giorni',
  'addMedicine.whenToTakeLabelText': 'Quando assumere',
  'addMedicine.beforeFoodOption': 'Prima dei pasti',
  'addMedicine.afterFoodOption': 'Dopo i pasti',
  'addMedicine.notificationsSectionLabel': 'Notifiche',
  'addMedicine.notificationSubtext':
      'Ricevi una notifica 5 minuti prima di ogni dose',
  'addMedicine.durationPickerTitle': 'Seleziona durata (in giorni)',
  'addMedicine.durationPickerItemText': '{days} giorni',
  'addMedicine.timesSelected': 'volte selezionate',
  'addMedicine.notificationsLabel': 'Notifiche',
  'addMedicine.enableDoseReminders': 'Attiva promemoria dosi',
  'addMedicine.remindersSubtext':
      'Ricevi una notifica 5 minuti prima di ogni dose',

  // Profile Page
  'personal_info': 'Informazioni personali',
  'preferences': 'Preferenze',
  'about_app': 'Info applicazione',
  'app_version': 'Versione app',
  'privacy_policy': 'Informativa privacy',
  'developer': 'Sviluppatore: Furkan Akif İŞLEK',
  'noEmail': 'Nessuna email trovata',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'Elimina account',
  'profile.deleteAccountImportantText':
      'Sei sicuro di voler eliminare il tuo account? Questa azione non può essere annullata.',
  'profile.cancel': 'Annulla',
  'profile.delete': 'Elimina',
  'profile.errorDeletingAccount': 'Errore nell\'eliminare l\'account',
  'profile.deleteAccountButton': 'Elimina account',

  // Profile Page
  'logout': 'Esci',
  'account': 'Account',
};
