// lib/utils/localization/ja_jp.dart

const Map<String, String> jaJP = {
  // General
  'general.appTitle': '薬リマインダー',
  'general.save': '保存',
  'general.cancel': 'キャンセル',
  'general.delete': '削除',
  'general.edit': '編集',
  'general.add': '追加',
  'general.confirm': '確認',
  'general.success': '成功',
  'general.error': 'エラー',
  'general.loading': '読み込み中...',
  'general.requiredField': 'この項目は必須です',
  'general.done': '完了',

  // Auth
  'auth.login': 'ログイン',
  'auth.signup': '新規登録',
  'auth.logout': 'ログアウト',
  'auth.email': 'メールアドレス',
  'auth.password': 'パスワード',
  'auth.loginButton': 'ログイン',
  'auth.signupButton': '登録',
  'auth.loginErrorTitle': 'ログイン失敗',
  'auth.signupErrorTitle': '登録失敗',
  'auth.unknownError': '不明なエラーが発生しました。',
  'auth.or': 'または',
  'auth.noAccount': 'アカウントをお持ちでない方は登録',
  'auth.haveAccount': 'すでにアカウントをお持ちの方はログイン',

  // Home / Medicine List
  'home.title': '私の薬',
  'home.addMedicine': '新しい薬を追加',
  'home.noMedicines': 'まだ薬が追加されていません。+をタップして追加してください！',
  'home.confirmDeleteTitle': '薬を削除',
  'home.confirmDeleteContent': '本当に{medicineName}を削除しますか？',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': '薬を追加',
  'addMedicine.titleEdit': '薬を編集',
  'addMedicine.nameLabel': '薬の名前',
  'addMedicine.nameHint': '例：パラセタモール',
  'addMedicine.typeLabel': '薬のタイプ/カテゴリー',
  'addMedicine.typeHint': '例：錠剤、シロップ、注射',
  'addMedicine.dosageLabel': '用量の量',
  'addMedicine.dosageHint': '例：1、2、500',
  'addMedicine.dosageUnitLabel': '用量の単位',
  'addMedicine.dosageUnitHint': '例：錠、mL、mg',
  'addMedicine.frequencyLabel': '頻度',
  'addMedicine.frequencyHint': '例：毎日、1日2回',
  'addMedicine.durationLabel': '期間（日数）',
  'addMedicine.durationHint': '例：7、14、30（継続的な場合は0）',
  'addMedicine.whenToTakeLabel': '服用タイミング/メモ',
  'addMedicine.whenToTakeHint': '例：食事と一緒に、就寝前',
  'addMedicine.startDateLabel': '開始日',
  'addMedicine.endDateLabel': '終了日（任意）',
  'addMedicine.selectDate': '日付を選択',
  'addMedicine.selectTime': '時間を選択',
  'addMedicine.timesLabel': '1日あたりの回数',
  'addMedicine.addTime': '時間を追加',
  'addMedicine.notesLabel': '追加メモ（任意）',
  'addMedicine.notesHint': '例：涼しい場所に保管',
  'addMedicine.enableNotificationsLabel': '服用リマインダーを有効にする',
  'addMedicine.errorNumeric': '有効な数字を入力してください',
  'addMedicine.addMedicine': '薬を追加',
  'addMedicine.save': '保存',
  'addMedicine.name': '薬の名前',
  'addMedicine.addMedicineHint': '薬の名前（例：パラセタモール）',
  'addMedicine.dosage': '用量',
  'addMedicine.dosageHint2': '量（例：500）',
  'addMedicine.dosageUnit': '単位（例：mg）',
  'addMedicine.category': 'カテゴリー',
  'addMedicine.frequency': '頻度と期間',
  'addMedicine.selectDoseTimes': '服用時間を選択',
  'addMedicine.times': '回選択済み',
  'addMedicine.selectDuration': '期間を選択',
  'addMedicine.days': '日',
  'addMedicine.whenToTake': '服用タイミング',
  'addMedicine.beforeFood': '食前',
  'addMedicine.afterFood': '食後',
  'addMedicine.notifications': '通知',
  'addMedicine.enableNotifications': '服用リマインダーを有効にする',
  'addMedicine.receiveNotification': '各服用の5分前に通知を受け取る',
  'addMedicine.doseTimesPickerTitle': '服用時間を選択',
  'addMedicine.done': '完了',

  // Medicine Controller Messages
  'medicine.addSuccess': '薬が正常に追加されました。',
  'medicine.updateSuccess': '薬が正常に更新されました。',
  'medicine.deleteSuccess': '薬が正常に削除されました。',
  'medicine.errorNeedTime': '少なくとも1つの時間を選択してください。',
  'medicine.saveMedicineSuccess': '薬が正常に保存されました。',
  'medicine.saveMedicineError': 'エラー',
  'medicine.saveMedicineErrorMessage': '薬の保存に失敗しました：{e}',
  'medicine.updateMedicineSuccess': '薬が正常に更新されました。',
  'medicine.updateMedicineError': 'エラー',
  'medicine.updateMedicineErrorMessage': '薬の更新に失敗しました：{e}',
  'medicine.deleteMedicineSuccess': '薬が正常に削除されました。',
  'medicine.deleteMedicineError': 'エラー',
  'medicine.deleteMedicineErrorMessage': '薬の削除に失敗しました：{e}',
  'medicine.withFood': '食事と一緒に',
  'medicine.deleteMedicineSuccessMessage': '薬が正常に削除されました。',
  'medicine.saveMedicineSuccessMessage': '薬が正常に保存されました。',

  // Settings Page
  'settings.title': '設定',
  'settings.language': '言語',
  'settings.selectLanguage': '言語を選択',
  'settings.profile': 'プロフィール',

  // Introduction Screen
  'introduction.skip': 'スキップ',
  'introduction.done': '完了',
  'introduction.next': '次へ',

  // Filter
  'filter.allTypes': 'すべてのタイプ',
  'filter.uncategorized': 'カテゴリなし',
  'filter.searchHint': '薬を検索...',
  'filter.noResultsForSearchAndType': '\"{query}\"の{type}での検索結果はありません',
  'filter.noResultsForSearch': '\"{query}\"の検索結果はありません',
  'filter.noResultsForType': 'タイプ\"{type}\"の結果はありません',

  // Medicine Card
  'card.treatmentCompleted': '治療完了',
  'card.nextDoseN_A': '次の服用：なし',
  'card.todayAt': '今日',
  'card.tomorrowAt': '明日',
  'card.at': '時',
  'card.nextDose': '次の服用：',
  'card.frequency.onceDaily': '1日1回',
  'card.frequency.twiceDaily': '1日2回',
  'card.frequency.thriceDaily': '1日3回',
  'card.frequency.timesDaily': '1日{count}回',
  'addMedicine.nameLabelText': '名前',
  'addMedicine.dosageLabelText': '用量',
  'addMedicine.dosageQuantityHint': '量（例：500）',
  'addMedicine.categoryLabel': 'カテゴリー',
  'addMedicine.frequencyDurationLabel': '頻度と期間',
  'addMedicine.selectDoseTimesPlaceholder': '服用時間を選択',
  'addMedicine.doseTimesBottomSheetTitle': '服用時間を選択',
  'addMedicine.timesSelectedInfo': '{count}回選択済み',
  'addMedicine.selectDurationPlaceholder': '期間を選択',
  'addMedicine.durationSelectedInfo': '{count}日',
  'addMedicine.whenToTakeLabelText': '服用タイミング',
  'addMedicine.beforeFoodOption': '食前',
  'addMedicine.afterFoodOption': '食後',
  'addMedicine.notificationsSectionLabel': '通知',
  'addMedicine.notificationSubtext': '各服用の5分前に通知を受け取る',
  'addMedicine.durationPickerTitle': '期間を選択（日数）',
  'addMedicine.durationPickerItemText': '{days}日',
  'addMedicine.timesSelected': '回選択済み',
  'addMedicine.notificationsLabel': '通知',
  'addMedicine.enableDoseReminders': '服用リマインダーを有効にする',
  'addMedicine.remindersSubtext': '各服用の5分前に通知を受け取る',

  // Profile Page
  'personal_info': '個人情報',
  'preferences': '設定',
  'about_app': 'アプリについて',
  'app_version': 'アプリバージョン',
  'privacy_policy': 'プライバシーポリシー',
  'developer': '開発者：Furkan Akif İŞLEK',
  'noEmail': 'メールが見つかりません',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'アカウントを削除',
  'profile.deleteAccountImportantText': '本当にアカウントを削除しますか？この操作は元に戻せません。',
  'profile.cancel': 'キャンセル',
  'profile.delete': '削除',
  'profile.errorDeletingAccount': 'アカウント削除中にエラーが発生しました',
  'profile.deleteAccountButton': 'アカウントを削除',

  // Profile Page
  'logout': 'ログアウト',
  'account': 'アカウント',
};
