// lib/utils/localization/ko_kr.dart

const Map<String, String> koKR = {
  // General
  'general.appTitle': '약 리마인더',
  'general.save': '저장',
  'general.cancel': '취소',
  'general.delete': '삭제',
  'general.edit': '편집',
  'general.add': '추가',
  'general.confirm': '확인',
  'general.success': '성공',
  'general.error': '오류',
  'general.loading': '로딩 중...',
  'general.requiredField': '이 필드는 필수입니다',
  'general.done': '완료',

  // Auth
  'auth.login': '로그인',
  'auth.signup': '회원가입',
  'auth.logout': '로그아웃',
  'auth.email': '이메일',
  'auth.password': '비밀번호',
  'auth.loginButton': '로그인',
  'auth.signupButton': '가입하기',
  'auth.loginErrorTitle': '로그인 실패',
  'auth.signupErrorTitle': '회원가입 실패',
  'auth.unknownError': '알 수 없는 오류가 발생했습니다.',
  'auth.or': '또는',
  'auth.noAccount': '계정이 없으신가요? 가입하기',
  'auth.haveAccount': '이미 계정이 있으신가요? 로그인',

  // Home / Medicine List
  'home.title': '내 약',
  'home.addMedicine': '새 약 추가',
  'home.noMedicines': '아직 추가된 약이 없습니다. +를 탭하여 추가하세요!',
  'home.confirmDeleteTitle': '약 삭제',
  'home.confirmDeleteContent': '{medicineName}을(를) 삭제하시겠습니까?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': '약 추가',
  'addMedicine.titleEdit': '약 편집',
  'addMedicine.nameLabel': '약 이름',
  'addMedicine.nameHint': '예: 파라세타몰',
  'addMedicine.typeLabel': '약 유형/카테고리',
  'addMedicine.typeHint': '예: 알약, 시럽, 주사',
  'addMedicine.dosageLabel': '복용량',
  'addMedicine.dosageHint': '예: 1, 2, 500',
  'addMedicine.dosageUnitLabel': '복용 단위',
  'addMedicine.dosageUnitHint': '예: 정, mL, mg',
  'addMedicine.frequencyLabel': '빈도',
  'addMedicine.frequencyHint': '예: 매일, 하루 두 번',
  'addMedicine.durationLabel': '기간 (일)',
  'addMedicine.durationHint': '예: 7, 14, 30 (계속 복용은 0)',
  'addMedicine.whenToTakeLabel': '복용 시간 / 메모',
  'addMedicine.whenToTakeHint': '예: 식사와 함께, 취침 전',
  'addMedicine.startDateLabel': '시작일',
  'addMedicine.endDateLabel': '종료일 (선택 사항)',
  'addMedicine.selectDate': '날짜 선택',
  'addMedicine.selectTime': '시간 선택',
  'addMedicine.timesLabel': '하루 복용 횟수',
  'addMedicine.addTime': '시간 추가',
  'addMedicine.notesLabel': '추가 메모 (선택 사항)',
  'addMedicine.notesHint': '예: 서늘한 곳에 보관',
  'addMedicine.enableNotificationsLabel': '복용 알림 활성화',
  'addMedicine.errorNumeric': '유효한 숫자를 입력하세요',
  'addMedicine.addMedicine': '약 추가',
  'addMedicine.save': '저장',
  'addMedicine.name': '약 이름',
  'addMedicine.addMedicineHint': '약 이름 (예: 파라세타몰)',
  'addMedicine.dosage': '복용량',
  'addMedicine.dosageHint2': '양 (예: 500)',
  'addMedicine.dosageUnit': '단위 (예: mg)',
  'addMedicine.category': '카테고리',
  'addMedicine.frequency': '빈도 & 기간',
  'addMedicine.selectDoseTimes': '복용 시간 선택',
  'addMedicine.times': '회 선택됨',
  'addMedicine.selectDuration': '기간 선택',
  'addMedicine.days': '일',
  'addMedicine.whenToTake': '복용 시간',
  'addMedicine.beforeFood': '식전',
  'addMedicine.afterFood': '식후',
  'addMedicine.notifications': '알림',
  'addMedicine.enableNotifications': '복용 알림 활성화',
  'addMedicine.receiveNotification': '각 복용 5분 전에 알림 받기',
  'addMedicine.doseTimesPickerTitle': '복용 시간 선택',
  'addMedicine.done': '완료',
  'addMedicine.deleteMedicine': '약 삭제',

  // Medicine Controller Messages
  'medicine.addSuccess': '약이 성공적으로 추가되었습니다.',
  'medicine.updateSuccess': '약이 성공적으로 업데이트되었습니다.',
  'medicine.deleteSuccess': '약이 성공적으로 삭제되었습니다.',
  'medicine.errorNeedTime': '최소 하나의 시간을 선택하세요.',
  'medicine.saveMedicineSuccess': '약이 성공적으로 저장되었습니다.',
  'medicine.saveMedicineError': '오류',
  'medicine.saveMedicineErrorMessage': '약 저장 실패: {e}',
  'medicine.updateMedicineSuccess': '약이 성공적으로 업데이트되었습니다.',
  'medicine.updateMedicineError': '오류',
  'medicine.updateMedicineErrorMessage': '약 업데이트 실패: {e}',
  'medicine.deleteMedicineSuccess': '약이 성공적으로 삭제되었습니다.',
  'medicine.deleteMedicineError': '오류',
  'medicine.deleteMedicineErrorMessage': '약 삭제 실패: {e}',
  'medicine.withFood': '식사와 함께',
  'medicine.deleteMedicineSuccessMessage': '약이 성공적으로 삭제되었습니다.',
  'medicine.saveMedicineSuccessMessage': '약이 성공적으로 저장되었습니다.',

  // Settings Page
  'settings.title': '설정',
  'settings.language': '언어',
  'settings.selectLanguage': '언어 선택',
  'settings.profile': '프로필',

  // Introduction Screen
  'introduction.skip': '건너뛰기',
  'introduction.done': '완료',
  'introduction.next': '다음',

  // Filter
  'filter.allTypes': '모든 유형',
  'filter.uncategorized': '분류되지 않음',
  'filter.searchHint': '약 검색...',
  'filter.noResultsForSearchAndType': '\"{query}\"에 대한 {type} 유형의 결과가 없습니다',
  'filter.noResultsForSearch': '\"{query}\"에 대한 결과가 없습니다',
  'filter.noResultsForType': '\"{type}\" 유형에 대한 결과가 없습니다',

  // Medicine Card
  'card.treatmentCompleted': '치료 완료',
  'card.nextDoseN_A': '다음 복용: 없음',
  'card.todayAt': '오늘',
  'card.tomorrowAt': '내일',
  'card.at': '시',
  'card.nextDose': '다음 복용:',
  'card.frequency.onceDaily': '하루 한 번',
  'card.frequency.twiceDaily': '하루 두 번',
  'card.frequency.thriceDaily': '하루 세 번',
  'card.frequency.timesDaily': '하루 {count}번',
  'addMedicine.nameLabelText': '이름',
  'addMedicine.dosageLabelText': '복용량',
  'addMedicine.dosageQuantityHint': '양 (예: 500)',
  'addMedicine.categoryLabel': '카테고리',
  'addMedicine.frequencyDurationLabel': '빈도 & 기간',
  'addMedicine.selectDoseTimesPlaceholder': '복용 시간 선택',
  'addMedicine.doseTimesBottomSheetTitle': '복용 시간 선택',
  'addMedicine.timesSelectedInfo': '{count}회 선택됨',
  'addMedicine.selectDurationPlaceholder': '기간 선택',
  'addMedicine.durationSelectedInfo': '{count}일',
  'addMedicine.whenToTakeLabelText': '복용 시간',
  'addMedicine.beforeFoodOption': '식전',
  'addMedicine.afterFoodOption': '식후',
  'addMedicine.notificationsSectionLabel': '알림',
  'addMedicine.notificationSubtext': '각 복용 5분 전에 알림 받기',
  'addMedicine.durationPickerTitle': '기간 선택 (일)',
  'addMedicine.durationPickerItemText': '{days}일',
  'addMedicine.timesSelected': '회 선택됨',
  'addMedicine.notificationsLabel': '알림',
  'addMedicine.enableDoseReminders': '복용 알림 활성화',
  'addMedicine.remindersSubtext': '각 복용 5분 전에 알림 받기',

  // Profile Page
  'personal_info': '개인 정보',
  'preferences': '환경설정',
  'about_app': '앱 정보',
  'app_version': '앱 버전',
  'privacy_policy': '개인정보 처리방침',
  'developer': '개발자: 푸르칸 아키프 이슬렉',
  'noEmail': '이메일이 없습니다',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': '계정 삭제',
  'profile.deleteAccountImportantText': '정말로 계정을 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
  'profile.cancel': '취소',
  'profile.delete': '삭제',
  'profile.errorDeletingAccount': '계정 삭제 중 오류 발생',
  'profile.deleteAccountButton': '계정 삭제',

  // Profile Page
  'logout': '로그아웃',
  'account': '계정',

  // Blog Page
  'Blog': '블로그',
  'Bir hata oluştu.': '오류가 발생했습니다.',
  'Blog yazısı bulunamadı.': '블로그 게시물을 찾을 수 없습니다.',
  'Şuan blog yok': '사용 가능한 블로그가 없습니다',
  'pills': '알약',
  'health': '건강',
  'lifeStyle': '라이프스타일',

  // Privacy Policy
  'privacy_policy_content':
      '<h3>약물 알림 - 개인정보 처리방침</h3><br><p><b>개인 정보 사용:</b><br>당사의 애플리케이션은 사용자의 개인 정보 보호에 최선을 다하고 있습니다. 약물 알림 앱에서는 약물 추적 및 알림을 위해 필요한 정보(이메일, 프로필 정보 및 약물 계획)를 수집합니다. 이 정보는 서비스 제공 및 개선을 위해 사용되며 제3자와 공유되지 않습니다.</p><br><p><b>데이터 저장 및 보안:</b><br>사용자 데이터는 암호화된 형식으로 안전한 서버에 저장됩니다. 약물 정보 및 개인 데이터는 강력한 보안 조치 하에 보호됩니다. 필요한 직원만이 귀하의 데이터에 접근할 수 있습니다.</p><br><p><b>사용자 권리:</b><br>사용자는 언제든지 계정 및 데이터를 보거나, 편집하거나, 삭제할 권리가 있습니다. 계정을 삭제하면 모든 데이터가 당사 시스템에서 영구적으로 제거됩니다.</p><br><p><b>쿠키 및 추적:</b><br>당사 애플리케이션은 사용자 경험을 향상시키기 위해 쿠키를 사용할 수 있습니다. 이러한 쿠키는 사용자 환경 설정 및 애플리케이션 사용 데이터를 저장합니다. 원하는 경우 브라우저 설정에서 쿠키를 비활성화할 수 있습니다.</p><br><p><b>알림:</b><br>당사 애플리케이션은 사용자가 승인한 약물 알림에 대해서만 알림을 보냅니다. 원치 않는 알림을 받지 않으며 설정 섹션에서 알림을 비활성화할 수 있습니다.</p><br><p><b>변경 사항:</b><br>당사의 개인정보 처리방침은 때때로 업데이트될 수 있습니다. 중요한 변경 사항이 있을 때 사용자에게 알립니다. 당사 애플리케이션을 사용함으로써 이 약관에 동의하게 됩니다.</p><br><p><b>연락처:</b><br>당사의 개인정보 처리방침에 관한 질문이 있으시면 언제든지 문의해 주십시오.</p>',

  // Introduction Page
  "introduction.page1.title": "약을 제때 복용하고, 건강을 지키세요",
  "introduction.page1.description":
      "바쁜 일상에서 약 복용 시간을 잊기 쉽습니다. 저희 앱을 사용하면 더 이상 어떤 약도 놓치지 않습니다. 약, 시간, 기간을 설정하면 – 저희가 제때 알려드립니다.",
  "introduction.page1.tip": "건강은 제때 복용한 한 알의 약부터 시작됩니다.",

  "introduction.page2.title": "건강을 추적하고, 정보를 얻으세요",
  "introduction.page2.description":
      "저희는 약 복용을 알려드릴 뿐만 아니라, 건강에 대한 유용한 정보도 제공합니다. 전문가가 지원하는 블로그 포스트로 일상 건강 습관을 강화하세요.",
  "introduction.page2.tip": "작은 정보가 큰 차이를 만들 수 있습니다.",

  "introduction.page3.title": "세계에 열려 있고, 당신에게 맞춤화되었습니다",
  "introduction.page3.description":
      "저희 앱은 16개 언어를 지원하여 모든 사람이 접근할 수 있습니다. 사용하기 쉬운 인터페이스로 몇 번의 탭만으로 약을 추가하고 생활을 더 편리하게 만드세요.",
  "introduction.page3.tip": "건강은 보편적이며, 저희도 그렇습니다.",

  "introduction.back": "이전",
  "introduction.start": "시작",

  // Register Page
  "register.register_to_medreminder_app": "약 알림 앱에 등록하기",
  "register.already_have_an_account": "이미 계정이 있으신가요? ",
  "register.sign_in": "로그인",
  "register.full_name": "귀하의 전체 이름",
  "register.surname": "귀하의 성",
  "register.your_email": "귀하의 이메일",
  "register.type_your_password": "비밀번호 입력",
  "register.re_type_your_password": "비밀번호 재입력",
  "register.register": "등록",
  "register.fill_all_fields": "모든 필드를 작성해주세요",
  "register.password_not_match": "비밀번호가 일치하지 않습니다",
  "register.error_occurred": "오류가 발생했습니다",

  // Login Page
  "login.invalid_email": "잘못된 이메일 주소",
  "login.user_disabled": "사용자가 비활성화되었습니다",
  "login.email_already_in_use": "이 이메일 주소는 이미 사용 중입니다",
  "login.wrong_password": "입력하신 정보가 올바르지 않습니다",
  "login.email_not_verified": "먼저 이메일 주소를 확인해주세요",
  "login.operation_not_allowed": "이 작업은 허용되지 않습니다",
  "login.error_occurred": "오류가 발생했습니다",
  "login.error_occured_google": "Google로 로그인 중 오류가 발생했습니다",
  "login.please_enter_your_email": "이메일 주소를 입력해주세요",
  "login.password_reset_email_sent": "비밀번호 재설정 이메일이 발송되었습니다",
  "login.login_into_your_account": "계정에 로그인하세요",
  "login.dont_have_an_account": "계정이 없으신가요? ",
  "login.sign_up": "가입하기",
  "login.your_email": "귀하의 이메일",
  "login.type_your_password": "비밀번호 입력",
  "login.login": "로그인",
  "login.forgot_password": "비밀번호를 잊으셨나요?",
  "login.or": "또는",
  "login.login_with_google": "Google로 로그인",

  // Menu Page
  "menu.myMedicines": "내 약",
  "menu.addMedicine": "약 추가",
  "menu.blogs": "블로그",
  "menu.profile": "프로필",

  'time_for_medicine': '약 복용 시간입니다!',
  'take_medicine_now': '지금 {medicineName}의 {dosageInfo}을(를) 복용하세요.',
};
