const Map<String, String> ptBR = {
  // General
  'general.appTitle': 'Lembrete de Medicamentos',
  'general.save': 'Salvar',
  'general.cancel': 'Cancelar',
  'general.delete': 'Excluir',
  'general.edit': 'Editar',
  'general.add': 'Adicionar',
  'general.confirm': 'Confirmar',
  'general.success': 'Sucesso',
  'general.error': 'Erro',
  'general.loading': 'Carregando...',
  'general.requiredField': 'Este campo é obrigatório',
  'general.done': 'Concluído',

  // Auth
  'auth.login': 'Entrar',
  'auth.signup': 'Cadastrar',
  'auth.logout': 'Sair',
  'auth.email': 'E-mail',
  'auth.password': 'Senha',
  'auth.loginButton': 'Entrar',
  'auth.signupButton': 'Cadastrar',
  'auth.loginErrorTitle': 'Falha no login',
  'auth.signupErrorTitle': 'Falha no cadastro',
  'auth.unknownError': 'Ocorreu um erro desconhecido.',
  'auth.or': 'OU',
  'auth.noAccount': 'Não tem uma conta? Cadastre-se',
  'auth.haveAccount': 'Já tem uma conta? Entre',

  // Home / Medicine List
  'home.title': 'Meus Medicamentos',
  'home.addMedicine': 'Adicionar Novo Medicamento',
  'home.noMedicines':
      'Nenhum medicamento adicionado ainda. Toque em + para adicionar um!',
  'home.confirmDeleteTitle': 'Excluir Medicamento',
  'home.confirmDeleteContent': 'Tem certeza que deseja excluir {medicineName}?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'Adicionar Medicamento',
  'addMedicine.titleEdit': 'Editar Medicamento',
  'addMedicine.nameLabel': 'Nome do Medicamento',
  'addMedicine.nameHint': 'ex: Paracetamol',
  'addMedicine.typeLabel': 'Tipo/Categoria do Medicamento',
  'addMedicine.typeHint': 'ex: Comprimido, Xarope, Injeção',
  'addMedicine.dosageLabel': 'Quantidade da Dose',
  'addMedicine.dosageHint': 'ex: 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'Unidade da Dose',
  'addMedicine.dosageUnitHint': 'ex: comprimido, mL, mg',
  'addMedicine.frequencyLabel': 'Frequência',
  'addMedicine.frequencyHint': 'ex: Diário, Duas vezes ao dia',
  'addMedicine.durationLabel': 'Duração (dias)',
  'addMedicine.durationHint': 'ex: 7, 14, 30 (0 para contínuo)',
  'addMedicine.whenToTakeLabel': 'Quando Tomar / Notas',
  'addMedicine.whenToTakeHint': 'ex: Com comida, Antes de dormir',
  'addMedicine.startDateLabel': 'Data de Início',
  'addMedicine.endDateLabel': 'Data de Término (Opcional)',
  'addMedicine.selectDate': 'Selecionar Data',
  'addMedicine.selectTime': 'Selecionar Hora',
  'addMedicine.timesLabel': 'Vezes por Dia',
  'addMedicine.addTime': 'Adicionar Hora',
  'addMedicine.notesLabel': 'Notas Adicionais (Opcional)',
  'addMedicine.notesHint': 'ex: Armazenar em local fresco',
  'addMedicine.enableNotificationsLabel': 'Ativar Lembretes de Dose',
  'addMedicine.errorNumeric': 'Por favor, insira um número válido',
  'addMedicine.addMedicine': 'Adicionar Medicamento',
  'addMedicine.save': 'Salvar',
  'addMedicine.name': 'Nome do Medicamento',
  'addMedicine.addMedicineHint': 'Nome do Medicamento (ex: Paracetamol)',
  'addMedicine.dosage': 'Dosagem',
  'addMedicine.dosageHint2': 'Quantidade (ex: 500)',
  'addMedicine.dosageUnit': 'Unidade (ex: mg)',
  'addMedicine.category': 'Categoria',
  'addMedicine.frequency': 'Frequência & Duração',
  'addMedicine.selectDoseTimes': 'Selecionar Horários de Dose',
  'addMedicine.times': 'vez(es) selecionada(s)',
  'addMedicine.selectDuration': 'Selecionar Duração',
  'addMedicine.days': 'dia(s)',
  'addMedicine.whenToTake': 'Quando Tomar',
  'addMedicine.beforeFood': 'Antes da Refeição',
  'addMedicine.afterFood': 'Depois da Refeição',
  'addMedicine.notifications': 'Notificações',
  'addMedicine.enableNotifications': 'Ativar Lembretes de Dose',
  'addMedicine.receiveNotification':
      'Receba uma notificação 5 minutos antes de cada dose',
  'addMedicine.doseTimesPickerTitle': 'Selecionar Horários de Dose',
  'addMedicine.done': 'Concluído',

  // Medicine Controller Messages
  'medicine.addSuccess': 'Medicamento adicionado com sucesso.',
  'medicine.updateSuccess': 'Medicamento atualizado com sucesso.',
  'medicine.deleteSuccess': 'Medicamento excluído com sucesso.',
  'medicine.errorNeedTime': 'Por favor, selecione pelo menos um horário.',
  'medicine.saveMedicineSuccess': 'Medicamento salvo com sucesso.',
  'medicine.saveMedicineError': 'Erro',
  'medicine.saveMedicineErrorMessage': 'Falha ao salvar medicamento: {e}',
  'medicine.updateMedicineSuccess': 'Medicamento atualizado com sucesso.',
  'medicine.updateMedicineError': 'Erro',
  'medicine.updateMedicineErrorMessage': 'Falha ao atualizar medicamento: {e}',
  'medicine.deleteMedicineSuccess': 'Medicamento excluído com sucesso.',
  'medicine.deleteMedicineError': 'Erro',
  'medicine.deleteMedicineErrorMessage': 'Falha ao excluir medicamento: {e}',
  'medicine.deleteMedicineSuccessMessage': 'Medicamento excluído com sucesso.',
  'medicine.saveMedicineSuccessMessage': 'Medicamento salvo com sucesso.',
  'medicine.withFood': 'Com Comida',

  // Settings Page
  'settings.title': 'Configurações',
  'settings.language': 'Idioma',
  'settings.selectLanguage': 'Selecionar Idioma',
  'settings.profile': 'Perfil',

  // Introduction Screen
  'introduction.skip': 'Pular',
  'introduction.done': 'Concluído',
  'introduction.next': 'Próximo',

  // Filter
  'filter.allTypes': 'Todos os Tipos',
  'filter.uncategorized': 'Sem Categoria',
  'filter.searchHint': 'Pesquisar Medicamentos...',
  'filter.noResultsForSearchAndType':
      'Nenhum resultado para \"{query}\" em {type}',
  'filter.noResultsForSearch': 'Nenhum resultado para \"{query}\"',
  'filter.noResultsForType': 'Nenhum resultado para o tipo \"{type}\"',

  // Medicine Card
  'card.treatmentCompleted': 'Tratamento Concluído',
  'card.nextDoseN_A': 'Próxima dose: N/A',
  'card.todayAt': 'Hoje às',
  'card.tomorrowAt': 'Amanhã às',
  'card.at': 'às',
  'card.nextDose': 'Próxima dose:',
  'card.frequency.onceDaily': 'Uma vez ao dia',
  'card.frequency.twiceDaily': 'Duas vezes ao dia',
  'card.frequency.thriceDaily': 'Três vezes ao dia',
  'card.frequency.timesDaily': '{count} vezes ao dia',
  'addMedicine.nameLabelText': 'Nome',
  'addMedicine.dosageLabelText': 'Dosagem',
  'addMedicine.dosageQuantityHint': 'Quantidade (ex: 500)',
  'addMedicine.categoryLabel': 'Categoria',
  'addMedicine.frequencyDurationLabel': 'Frequência & Duração',
  'addMedicine.selectDoseTimesPlaceholder': 'Selecionar Horários de Dose',
  'addMedicine.doseTimesBottomSheetTitle': 'Selecionar Horários de Dose',
  'addMedicine.timesSelectedInfo': '{count} horário(s) selecionado(s)',
  'addMedicine.selectDurationPlaceholder': 'Selecionar Duração',
  'addMedicine.durationSelectedInfo': '{count} dia(s)',
  'addMedicine.whenToTakeLabelText': 'Quando Tomar',
  'addMedicine.beforeFoodOption': 'Antes da Refeição',
  'addMedicine.afterFoodOption': 'Depois da Refeição',
  'addMedicine.notificationsSectionLabel': 'Notificações',
  'addMedicine.notificationSubtext':
      'Receba uma notificação 5 minutos antes de cada dose',
  'addMedicine.durationPickerTitle': 'Selecionar Duração (em dias)',
  'addMedicine.durationPickerItemText': '{days} dia(s)',
  'addMedicine.timesSelected': 'vezes selecionadas',
  'addMedicine.notificationsLabel': 'Notificações',
  'addMedicine.enableDoseReminders': 'Ativar Lembretes de Dose',
  'addMedicine.remindersSubtext':
      'Receba uma notificação 5 minutos antes de cada dose',

  // Profile Page
  'personal_info': 'Informações Pessoais',
  'preferences': 'Preferências',
  'about_app': 'Sobre o Aplicativo',
  'app_version': 'Versão do Aplicativo',
  'privacy_policy': 'Política de Privacidade',
  'developer': 'Desenvolvedor: Furkan Akif İŞLEK',
  'noEmail': 'Nenhum e-mail encontrado',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'Excluir Conta',
  'profile.deleteAccountImportantText':
      'Tem certeza que deseja excluir sua conta? Esta ação não pode ser desfeita.',
  'profile.cancel': 'Cancelar',
  'profile.delete': 'Excluir',
  'profile.errorDeletingAccount': 'Erro ao excluir a conta',
  'profile.deleteAccountButton': 'Excluir Conta',

  // Profile Page
  'logout': 'Sair',
  'account': 'Conta',
};
