// lib/utils/localization/ru_ru.dart

const Map<String, String> ruRU = {
  // General
  'general.appTitle': 'Напоминание о лекарствах',
  'general.save': 'Сохранить',
  'general.cancel': 'Отмена',
  'general.delete': 'Удалить',
  'general.edit': 'Редактировать',
  'general.add': 'Добавить',
  'general.confirm': 'Подтвердить',
  'general.success': 'Успешно',
  'general.error': 'Ошибка',
  'general.loading': 'Загрузка...',
  'general.requiredField': 'Это поле обязательно к заполнению',

  // Auth
  'auth.login': 'Вход',
  'auth.signup': 'Регистрация',
  'auth.logout': 'Выход',
  'auth.email': 'Электронная почта',
  'auth.password': 'Пароль',
  'auth.loginButton': 'Войти',
  'auth.signupButton': 'Зарегистрироваться',
  'auth.loginErrorTitle': 'Ошибка входа',
  'auth.signupErrorTitle': 'Ошибка регистрации',
  'auth.unknownError': 'Произошла неизвестная ошибка.',
  'auth.or': 'ИЛИ',
  'auth.noAccount': 'Нет аккаунта? Зарегистрируйтесь',
  'auth.haveAccount': 'Уже есть аккаунт? Войдите',

  // Home / Medicine List
  'home.title': 'Мои лекарства',
  'home.addMedicine': 'Добавить новое лекарство',
  'home.noMedicines': 'Лекарства еще не добавлены. Нажмите +, чтобы добавить!',
  'home.confirmDeleteTitle': 'Удалить лекарство',
  'home.confirmDeleteContent': 'Вы уверены, что хотите удалить {medicineName}?',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': 'Добавить лекарство',
  'addMedicine.titleEdit': 'Редактировать лекарство',
  'addMedicine.nameLabel': 'Название лекарства',
  'addMedicine.nameHint': 'например, Парацетамол',
  'addMedicine.typeLabel': 'Тип/Категория лекарства',
  'addMedicine.typeHint': 'например, Таблетки, Сироп, Инъекция',
  'addMedicine.dosageLabel': 'Количество дозы',
  'addMedicine.dosageHint': 'например, 1, 2, 500',
  'addMedicine.dosageUnitLabel': 'Единица дозы',
  'addMedicine.dosageUnitHint': 'например, таблетки, мл, мг',
  'addMedicine.frequencyLabel': 'Частота',
  'addMedicine.frequencyHint': 'например, Ежедневно, Дважды в день',
  'addMedicine.durationLabel': 'Продолжительность (дни)',
  'addMedicine.durationHint': 'например, 7, 14, 30 (0 для постоянного приема)',
  'addMedicine.whenToTakeLabel': 'Когда принимать / Примечания',
  'addMedicine.whenToTakeHint': 'например, С едой, Перед сном',
  'addMedicine.startDateLabel': 'Дата начала',
  'addMedicine.endDateLabel': 'Дата окончания (необязательно)',
  'addMedicine.selectDate': 'Выбрать дату',
  'addMedicine.selectTime': 'Выбрать время',
  'addMedicine.timesLabel': 'Раз в день',
  'addMedicine.addTime': 'Добавить время',
  'addMedicine.notesLabel': 'Дополнительные примечания (необязательно)',
  'addMedicine.notesHint': 'например, Хранить в прохладном месте',
  'addMedicine.enableNotificationsLabel': 'Включить напоминания о дозах',
  'addMedicine.errorNumeric': 'Пожалуйста, введите действительное число',
  'addMedicine.addMedicine': 'Добавить лекарство',
  'addMedicine.save': 'Сохранить',
  'addMedicine.name': 'Название лекарства',
  'addMedicine.addMedicineHint': 'Название лекарства (например, Парацетамол)',
  'addMedicine.dosage': 'Дозировка',
  'addMedicine.dosageHint2': 'Количество (например, 500)',
  'addMedicine.dosageUnit': 'Единица (например, мг)',
  'addMedicine.category': 'Категория',
  'addMedicine.frequency': 'Частота и продолжительность',
  'addMedicine.selectDoseTimes': 'Выбрать время дозы',
  'addMedicine.times': 'раз(а) выбрано',
  'addMedicine.selectDuration': 'Выбрать продолжительность',
  'addMedicine.days': 'день(дней)',
  'addMedicine.whenToTake': 'Когда принимать',
  'addMedicine.beforeFood': 'До еды',
  'addMedicine.afterFood': 'После еды',
  'addMedicine.notifications': 'Уведомления',
  'addMedicine.enableNotifications': 'Включить напоминания о дозах',
  'addMedicine.receiveNotification':
      'Получать уведомление за 5 минут до каждой дозы',
  'addMedicine.doseTimesPickerTitle': 'Выбрать время дозы',
  'addMedicine.done': 'Готово',

  // Medicine Controller Messages
  'medicine.addSuccess': 'Лекарство успешно добавлено.',
  'medicine.updateSuccess': 'Лекарство успешно обновлено.',
  'medicine.deleteSuccess': 'Лекарство успешно удалено.',
  'medicine.errorNeedTime': 'Пожалуйста, выберите хотя бы одно время.',
  'medicine.saveMedicineSuccess': 'Лекарство успешно сохранено.',
  'medicine.saveMedicineError': 'Ошибка',
  'medicine.saveMedicineErrorMessage': 'Не удалось сохранить лекарство: {e}',
  'medicine.updateMedicineSuccess': 'Лекарство успешно обновлено.',
  'medicine.updateMedicineError': 'Ошибка',
  'medicine.updateMedicineErrorMessage': 'Не удалось обновить лекарство: {e}',
  'medicine.deleteMedicineSuccess': 'Лекарство успешно удалено.',
  'medicine.deleteMedicineError': 'Ошибка',
  'medicine.deleteMedicineErrorMessage': 'Не удалось удалить лекарство: {e}',
  'medicine.withFood': 'С едой',
  'medicine.deleteMedicineSuccessMessage': 'Лекарство успешно удалено.',

  // Settings Page
  'settings.title': 'Настройки',
  'settings.language': 'Язык',
  'settings.selectLanguage': 'Выбрать язык',
  'settings.profile': 'Профиль',

  // Introduction Screen
  'introduction.skip': 'Пропустить',
  'introduction.done': 'Готово',
  'introduction.next': 'Далее',

  // Filter
  'filter.allTypes': 'Все типы',
  'filter.uncategorized': 'Без категории',
  'filter.searchHint': 'Поиск лекарств...',
  'filter.noResultsForSearchAndType':
      'Нет результатов для \"{query}\" в {type}',
  'filter.noResultsForSearch': 'Нет результатов для \"{query}\"',
  'filter.noResultsForType': 'Нет результатов для типа \"{type}\"',

  // Medicine Card
  'card.treatmentCompleted': 'Лечение завершено',
  'card.nextDoseN_A': 'Следующая доза: Н/Д',
  'card.todayAt': 'Сегодня в',
  'card.tomorrowAt': 'Завтра в',
  'card.at': 'в',
  'card.nextDose': 'Следующая доза:',
  'card.frequency.onceDaily': 'Один раз в день',
  'card.frequency.twiceDaily': 'Два раза в день',
  'card.frequency.thriceDaily': 'Три раза в день',
  'card.frequency.timesDaily': '{count} раз(а) в день',
  'addMedicine.nameLabelText': 'Название',
  'addMedicine.dosageLabelText': 'Дозировка',
  'addMedicine.dosageQuantityHint': 'Количество (например, 500)',
  'addMedicine.categoryLabel': 'Категория',
  'addMedicine.frequencyDurationLabel': 'Частота и продолжительность',
  'addMedicine.selectDoseTimesPlaceholder': 'Выбрать время дозы',
  'addMedicine.doseTimesBottomSheetTitle': 'Выбрать время дозы',
  'addMedicine.timesSelectedInfo': '{count} время(времени) выбрано',
  'addMedicine.selectDurationPlaceholder': 'Выбрать продолжительность',
  'addMedicine.durationSelectedInfo': '{count} день(дней)',
  'addMedicine.whenToTakeLabelText': 'Когда принимать',
  'addMedicine.beforeFoodOption': 'До еды',
  'addMedicine.afterFoodOption': 'После еды',
  'addMedicine.notificationsSectionLabel': 'Уведомления',
  'addMedicine.notificationSubtext':
      'Получать уведомление за 5 минут до каждой дозы',
  'addMedicine.durationPickerTitle': 'Выбрать продолжительность (в днях)',
  'addMedicine.durationPickerItemText': '{days} день(дней)',
  'addMedicine.timesSelected': 'раз(а) выбрано',
  'addMedicine.notificationsLabel': 'Уведомления',
  'addMedicine.enableDoseReminders': 'Включить напоминания о дозах',
  'addMedicine.remindersSubtext':
      'Получать уведомление за 5 минут до каждой дозы',

  // Profile Page
  'personal_info': 'Личная информация',
  'preferences': 'Предпочтения',
  'about_app': 'О приложении',
  'app_version': 'Версия приложения',
  'privacy_policy': 'Политика конфиденциальности',
  'developer': 'Разработчик: Furkan Akif İŞLEK',
  'noEmail': 'Электронная почта не найдена',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': 'Удалить аккаунт',
  'profile.deleteAccountImportantText':
      'Вы уверены, что хотите удалить свой аккаунт? Это действие нельзя отменить.',
  'profile.cancel': 'Отмена',
  'profile.delete': 'Удалить',
  'profile.errorDeletingAccount': 'Ошибка при удалении аккаунта',
  'profile.deleteAccountButton': 'Удалить аккаунт',

  // Profile Page
  'logout': 'Выйти',
  'account': 'Аккаунт',
};
