// lib/utils/localization/zh_cn.dart

const Map<String, String> zhCN = {
  // General
  'general.appTitle': '药物提醒',
  'general.save': '保存',
  'general.cancel': '取消',
  'general.delete': '删除',
  'general.edit': '编辑',
  'general.add': '添加',
  'general.confirm': '确认',
  'general.success': '成功',
  'general.error': '错误',
  'general.loading': '加载中...',
  'general.requiredField': '此字段为必填项',
  'general.done': '完成',

  // Auth
  'auth.login': '登录',
  'auth.signup': '注册',
  'auth.logout': '退出登录',
  'auth.email': '电子邮箱',
  'auth.password': '密码',
  'auth.loginButton': '登录',
  'auth.signupButton': '注册',
  'auth.loginErrorTitle': '登录失败',
  'auth.signupErrorTitle': '注册失败',
  'auth.unknownError': '发生未知错误。',
  'auth.or': '或',
  'auth.noAccount': '没有账户？注册',
  'auth.haveAccount': '已有账户？登录',
  'auth.checkEmail': '检查您的电子邮件',
  'auth.resetPasswordInfo': '我们已发送信息\n 以重置您的密码',
  'auth.registerSuccessInfo': '注册成功。请使用发送到您电子邮件地址的链接\n 确认您的账户。',
  'auth.resetPassword': '重置密码',
  'auth.resetPasswordInstructions': '输入您的电子邮件地址，我们将向您发送有关如何重置密码的进一步说明。',
  'auth.yourEmail': '您的电子邮件',
  'auth.resetButton': '重置密码',
  'auth.emailRequired': '请输入您的电子邮件地址。',

  // Home / Medicine List
  'home.title': '我的药物',
  'home.addMedicine': '添加新药物',
  'home.noMedicines': '还没有添加药物。点击 + 添加一个！',
  'home.confirmDeleteTitle': '删除药物',
  'home.confirmDeleteContent': '您确定要删除 {medicineName} 吗？',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': '添加药物',
  'addMedicine.titleEdit': '编辑药物',
  'addMedicine.nameLabel': '药物名称',
  'addMedicine.nameHint': '例如：扑热息痛',
  'addMedicine.typeLabel': '药物类型/类别',
  'addMedicine.typeHint': '例如：片剂、糖浆、注射剂',
  'addMedicine.dosageLabel': '剂量数量',
  'addMedicine.dosageHint': '例如：1、2、500',
  'addMedicine.dosageUnitLabel': '剂量单位',
  'addMedicine.dosageUnitHint': '例如：片、毫升、毫克',
  'addMedicine.frequencyLabel': '频率',
  'addMedicine.frequencyHint': '例如：每天、每天两次',
  'addMedicine.durationLabel': '持续时间（天）',
  'addMedicine.durationHint': '例如：7、14、30（0表示持续）',
  'addMedicine.whenToTakeLabel': '服用时间/备注',
  'addMedicine.whenToTakeHint': '例如：随餐、睡前',
  'addMedicine.startDateLabel': '开始日期',
  'addMedicine.endDateLabel': '结束日期（可选）',
  'addMedicine.selectDate': '选择日期',
  'addMedicine.selectTime': '选择时间',
  'addMedicine.timesLabel': '每天次数',
  'addMedicine.addTime': '添加时间',
  'addMedicine.notesLabel': '附加说明（可选）',
  'addMedicine.notesHint': '例如：存放在阴凉处',
  'addMedicine.enableNotificationsLabel': '启用剂量提醒',
  'addMedicine.errorNumeric': '请输入有效数字',
  'addMedicine.addMedicine': '添加药物',
  'addMedicine.save': '保存',
  'addMedicine.name': '药物名称',
  'addMedicine.addMedicineHint': '药物名称（例如：扑热息痛）',
  'addMedicine.dosage': '剂量',
  'addMedicine.dosageHint2': '数量（例如：500）',
  'addMedicine.dosageUnit': '单位（例如：毫克）',
  'addMedicine.category': '类别',
  'addMedicine.frequency': '频率和持续时间',
  'addMedicine.selectDoseTimes': '选择剂量时间',
  'addMedicine.times': '次已选择',
  'addMedicine.selectDuration': '选择持续时间',
  'addMedicine.days': '天',
  'addMedicine.whenToTake': '何时服用',
  'addMedicine.beforeFood': '饭前',
  'addMedicine.afterFood': '饭后',
  'addMedicine.notifications': '通知',
  'addMedicine.enableNotifications': '启用剂量提醒',
  'addMedicine.receiveNotification': '在每次服药前5分钟收到通知',
  'addMedicine.doseTimesPickerTitle': '选择剂量时间',
  'addMedicine.done': '完成',
  'addMedicine.deleteMedicine': '删除药物',

  // Medicine Controller Messages
  'medicine.addSuccess': '药物添加成功。',
  'medicine.updateSuccess': '药物更新成功。',
  'medicine.deleteSuccess': '药物删除成功。',
  'medicine.errorNeedTime': '请至少选择一个时间。',
  'medicine.saveMedicineSuccess': '药物保存成功。',
  'medicine.saveMedicineError': '错误',
  'medicine.saveMedicineErrorMessage': '保存药物失败：{e}',
  'medicine.updateMedicineSuccess': '药物更新成功。',
  'medicine.updateMedicineError': '错误',
  'medicine.updateMedicineErrorMessage': '更新药物失败：{e}',
  'medicine.deleteMedicineSuccess': '药物删除成功。',
  'medicine.deleteMedicineError': '错误',
  'medicine.deleteMedicineErrorMessage': '删除药物失败：{e}',
  'medicine.withFood': '随餐',
  'medicine.deleteMedicineSuccessMessage': '药物删除成功。',
  'medicine.saveMedicineSuccessMessage': '药品保存成功。',

  // Settings Page
  'settings.title': '设置',
  'settings.language': '语言',
  'settings.selectLanguage': '选择语言',
  'settings.profile': '个人资料',

  // Introduction Screen
  'introduction.skip': '跳过',
  'introduction.done': '完成',
  'introduction.next': '下一步',

  // Filter
  'filter.allTypes': '所有类型',
  'filter.uncategorized': '未分类',
  'filter.searchHint': '搜索药物...',
  'filter.noResultsForSearchAndType': '在 {type} 中没有找到 \"{query}\" 的结果',
  'filter.noResultsForSearch': '没有找到 \"{query}\" 的结果',
  'filter.noResultsForType': '没有找到 \"{type}\" 类型的结果',

  // Medicine Card
  'card.treatmentCompleted': '治疗已完成',
  'card.nextDoseN_A': '下一剂量：无',
  'card.todayAt': '今天',
  'card.tomorrowAt': '明天',
  'card.at': '于',
  'card.nextDose': '下一剂量：',
  'card.frequency.onceDaily': '每天一次',
  'card.frequency.twiceDaily': '每天两次',
  'card.frequency.thriceDaily': '每天三次',
  'card.frequency.timesDaily': '每天 {count} 次',
  'addMedicine.nameLabelText': '名称',
  'addMedicine.dosageLabelText': '剂量',
  'addMedicine.dosageQuantityHint': '数量（例如：500）',
  'addMedicine.categoryLabel': '类别',
  'addMedicine.frequencyDurationLabel': '频率和持续时间',
  'addMedicine.selectDoseTimesPlaceholder': '选择剂量时间',
  'addMedicine.doseTimesBottomSheetTitle': '选择剂量时间',
  'addMedicine.timesSelectedInfo': '已选择 {count} 个时间',
  'addMedicine.selectDurationPlaceholder': '选择持续时间',
  'addMedicine.durationSelectedInfo': '{count} 天',
  'addMedicine.whenToTakeLabelText': '何时服用',
  'addMedicine.beforeFoodOption': '饭前',
  'addMedicine.afterFoodOption': '饭后',
  'addMedicine.notificationsSectionLabel': '通知',
  'addMedicine.notificationSubtext': '在每次服药前5分钟收到通知',
  'addMedicine.durationPickerTitle': '选择持续时间（天）',
  'addMedicine.durationPickerItemText': '{days} 天',
  'addMedicine.timesSelected': '次已选择',
  'addMedicine.notificationsLabel': '通知',
  'addMedicine.enableDoseReminders': '启用剂量提醒',
  'addMedicine.remindersSubtext': '在每次服药前5分钟收到通知',

  // Profile Page
  'personal_info': '个人信息',
  'preferences': '偏好设置',
  'about_app': '关于应用',
  'app_version': '应用版本',
  'privacy_policy': '隐私政策',
  'developer': '开发者：福坎·阿基夫·伊斯莱克',
  'noEmail': '未找到电子邮箱',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': '删除账户',
  'profile.deleteAccountImportantText': '您确定要删除您的账户吗？此操作无法撤销。',
  'profile.cancel': '取消',
  'profile.delete': '删除',
  'profile.errorDeletingAccount': '删除账户时出错',
  'profile.deleteAccountButton': '删除账户',

  // Profile Page
  'logout': '退出登录',
  'account': '账户',

  // Blog Page
  'Blog': '博客',
  'Bir hata oluştu.': '发生错误。',
  'Blog yazısı bulunamadı.': '未找到博客文章。',
  'Şuan blog yok': '没有可用的博客',
  'pills': '药丸',
  'health': '健康',
  'lifeStyle': '生活方式',

  // Privacy Policy
  'privacy_policy_content':
      '<h3>药物提醒 - 隐私政策</h3><br><p><b>个人信息使用：</b><br>我们的应用程序致力于保护用户的隐私。在我们的药物提醒应用程序中，我们收集药物跟踪和提醒所需的必要信息（电子邮件、个人资料信息和药物计划）。这些信息用于提供和改进我们的服务，不会与第三方共享。</p><br><p><b>数据存储和安全：</b><br>您的用户数据以加密格式存储在安全服务器上。您的药物信息和个人数据受到强大的安全措施保护。只有必要的人员才能访问您的数据。</p><br><p><b>用户权利：</b><br>用户有权随时查看、编辑或删除他们的账户和数据。当您删除账户时，您的所有数据将从我们的系统中永久删除。</p><br><p><b>Cookie和跟踪：</b><br>我们的应用程序可能使用Cookie来改善用户体验。这些Cookie存储用户偏好和应用程序使用数据。如果您愿意，可以从浏览器设置中禁用Cookie。</p><br><p><b>通知：</b><br>我们的应用程序仅发送用户批准的药物提醒通知。您不会收到不需要的通知，并且可以从设置部分禁用通知。</p><br><p><b>变更：</b><br>我们的隐私政策可能会不时更新。当有重大变化时，用户将会收到通知。使用我们的应用程序即表示您同意这些条款。</p><br><p><b>联系：</b><br>如有关于我们隐私政策的任何问题，请联系我们。</p>',

  // Introduction Page
  "introduction.page1.title": "按时服药，守护健康",
  "introduction.page1.description":
      "在忙碌的生活中，很容易忘记服药时间。有了我们的应用，您再也不会错过任何一剂药物。设置您的药物、时间和持续时间 – 我们会及时提醒您。",
  "introduction.page1.tip": "健康始于按时服用的一剂关爱。",

  "introduction.page2.title": "跟踪健康，保持信息畅通",
  "introduction.page2.description":
      "我们不仅提醒您，还提供有关您健康的有用信息。通过专家支持的博客文章，增强您的日常健康习惯。",
  "introduction.page2.tip": "一点小信息可能带来巨大的改变。",

  "introduction.page3.title": "面向世界，为您定制",
  "introduction.page3.description":
      "我们的应用支持16种语言，让每个人都能使用。凭借其易用的界面，只需几次点击即可添加您的药物，让生活更加便捷。",
  "introduction.page3.tip": "健康是普遍的，我们也是如此。",

  "introduction.back": "返回",
  "introduction.start": "开始",

  // Register Page
  "register.register_to_medreminder_app": "注册Amina Dose应用",
  "register.already_have_an_account": "已有账户？ ",
  "register.sign_in": "登录",
  "register.full_name": "您的全名",
  "register.surname": "您的姓氏",
  "register.your_email": "您的电子邮箱",
  "register.type_your_password": "输入您的密码",
  "register.re_type_your_password": "重新输入您的密码",
  "register.register": "注册",
  "register.fill_all_fields": "请填写所有字段",
  "register.password_not_match": "密码不匹配",
  "register.error_occurred": "发生错误",

  // Login Page
  "login.invalid_email": "无效的电子邮箱地址",
  "login.user_disabled": "用户已被禁用",
  "login.email_already_in_use": "该电子邮箱地址已被使用",
  "login.wrong_password": "您输入的信息不正确",
  "login.email_not_verified": "请先验证您的电子邮箱地址",
  "login.operation_not_allowed": "不允许此操作",
  "login.error_occurred": "发生错误",
  "login.error_occured_google": "使用谷歌登录时发生错误",
  "login.please_enter_your_email": "请输入您的电子邮箱地址",
  "login.password_reset_email_sent": "密码重置邮件已发送",
  "login.login_into_your_account": "登录您的账户",
  "login.dont_have_an_account": "没有账户？ ",
  "login.sign_up": "注册",
  "login.your_email": "您的电子邮箱",
  "login.type_your_password": "输入您的密码",
  "login.login": "登录",
  "login.forgot_password": "忘记密码？",
  "login.or": "或",
  "login.login_with_google": "使用谷歌登录",

  // Menu Page
  "menu.myMedicines": "我的药物",
  "menu.addMedicine": "添加药物",
  "menu.blogs": "博客",
  "menu.profile": "资料",

  'time_for_medicine': '该吃药了！',
  'take_medicine_now': '现在服用您的{dosageInfo}{medicineName}。',
};
