// lib/utils/localization/zh_cn.dart

const Map<String, String> zhCN = {
  // General
  'general.appTitle': '药物提醒',
  'general.save': '保存',
  'general.cancel': '取消',
  'general.delete': '删除',
  'general.edit': '编辑',
  'general.add': '添加',
  'general.confirm': '确认',
  'general.success': '成功',
  'general.error': '错误',
  'general.loading': '加载中...',
  'general.requiredField': '此字段为必填项',
  'general.done': '完成',

  // Auth
  'auth.login': '登录',
  'auth.signup': '注册',
  'auth.logout': '退出登录',
  'auth.email': '电子邮箱',
  'auth.password': '密码',
  'auth.loginButton': '登录',
  'auth.signupButton': '注册',
  'auth.loginErrorTitle': '登录失败',
  'auth.signupErrorTitle': '注册失败',
  'auth.unknownError': '发生未知错误。',
  'auth.or': '或',
  'auth.noAccount': '没有账户？注册',
  'auth.haveAccount': '已有账户？登录',

  // Home / Medicine List
  'home.title': '我的药物',
  'home.addMedicine': '添加新药物',
  'home.noMedicines': '还没有添加药物。点击 + 添加一个！',
  'home.confirmDeleteTitle': '删除药物',
  'home.confirmDeleteContent': '您确定要删除 {medicineName} 吗？',

  // Add/Edit Medicine Page
  'addMedicine.titleAdd': '添加药物',
  'addMedicine.titleEdit': '编辑药物',
  'addMedicine.nameLabel': '药物名称',
  'addMedicine.nameHint': '例如：扑热息痛',
  'addMedicine.typeLabel': '药物类型/类别',
  'addMedicine.typeHint': '例如：片剂、糖浆、注射剂',
  'addMedicine.dosageLabel': '剂量数量',
  'addMedicine.dosageHint': '例如：1、2、500',
  'addMedicine.dosageUnitLabel': '剂量单位',
  'addMedicine.dosageUnitHint': '例如：片、毫升、毫克',
  'addMedicine.frequencyLabel': '频率',
  'addMedicine.frequencyHint': '例如：每天、每天两次',
  'addMedicine.durationLabel': '持续时间（天）',
  'addMedicine.durationHint': '例如：7、14、30（0表示持续）',
  'addMedicine.whenToTakeLabel': '服用时间/备注',
  'addMedicine.whenToTakeHint': '例如：随餐、睡前',
  'addMedicine.startDateLabel': '开始日期',
  'addMedicine.endDateLabel': '结束日期（可选）',
  'addMedicine.selectDate': '选择日期',
  'addMedicine.selectTime': '选择时间',
  'addMedicine.timesLabel': '每天次数',
  'addMedicine.addTime': '添加时间',
  'addMedicine.notesLabel': '附加说明（可选）',
  'addMedicine.notesHint': '例如：存放在阴凉处',
  'addMedicine.enableNotificationsLabel': '启用剂量提醒',
  'addMedicine.errorNumeric': '请输入有效数字',
  'addMedicine.addMedicine': '添加药物',
  'addMedicine.save': '保存',
  'addMedicine.name': '药物名称',
  'addMedicine.addMedicineHint': '药物名称（例如：扑热息痛）',
  'addMedicine.dosage': '剂量',
  'addMedicine.dosageHint2': '数量（例如：500）',
  'addMedicine.dosageUnit': '单位（例如：毫克）',
  'addMedicine.category': '类别',
  'addMedicine.frequency': '频率和持续时间',
  'addMedicine.selectDoseTimes': '选择剂量时间',
  'addMedicine.times': '次已选择',
  'addMedicine.selectDuration': '选择持续时间',
  'addMedicine.days': '天',
  'addMedicine.whenToTake': '何时服用',
  'addMedicine.beforeFood': '饭前',
  'addMedicine.afterFood': '饭后',
  'addMedicine.notifications': '通知',
  'addMedicine.enableNotifications': '启用剂量提醒',
  'addMedicine.receiveNotification': '在每次服药前5分钟收到通知',
  'addMedicine.doseTimesPickerTitle': '选择剂量时间',
  'addMedicine.done': '完成',

  // Medicine Controller Messages
  'medicine.addSuccess': '药物添加成功。',
  'medicine.updateSuccess': '药物更新成功。',
  'medicine.deleteSuccess': '药物删除成功。',
  'medicine.errorNeedTime': '请至少选择一个时间。',
  'medicine.saveMedicineSuccess': '药物保存成功。',
  'medicine.saveMedicineError': '错误',
  'medicine.saveMedicineErrorMessage': '保存药物失败：{e}',
  'medicine.updateMedicineSuccess': '药物更新成功。',
  'medicine.updateMedicineError': '错误',
  'medicine.updateMedicineErrorMessage': '更新药物失败：{e}',
  'medicine.deleteMedicineSuccess': '药物删除成功。',
  'medicine.deleteMedicineError': '错误',
  'medicine.deleteMedicineErrorMessage': '删除药物失败：{e}',
  'medicine.withFood': '随餐',
  'medicine.deleteMedicineSuccessMessage': '药物删除成功。',
  'medicine.saveMedicineSuccessMessage': '药品保存成功。',

  // Settings Page
  'settings.title': '设置',
  'settings.language': '语言',
  'settings.selectLanguage': '选择语言',
  'settings.profile': '个人资料',

  // Introduction Screen
  'introduction.skip': '跳过',
  'introduction.done': '完成',
  'introduction.next': '下一步',

  // Filter
  'filter.allTypes': '所有类型',
  'filter.uncategorized': '未分类',
  'filter.searchHint': '搜索药物...',
  'filter.noResultsForSearchAndType': '在 {type} 中没有找到 \"{query}\" 的结果',
  'filter.noResultsForSearch': '没有找到 \"{query}\" 的结果',
  'filter.noResultsForType': '没有找到 \"{type}\" 类型的结果',

  // Medicine Card
  'card.treatmentCompleted': '治疗已完成',
  'card.nextDoseN_A': '下一剂量：无',
  'card.todayAt': '今天',
  'card.tomorrowAt': '明天',
  'card.at': '于',
  'card.nextDose': '下一剂量：',
  'card.frequency.onceDaily': '每天一次',
  'card.frequency.twiceDaily': '每天两次',
  'card.frequency.thriceDaily': '每天三次',
  'card.frequency.timesDaily': '每天 {count} 次',
  'addMedicine.nameLabelText': '名称',
  'addMedicine.dosageLabelText': '剂量',
  'addMedicine.dosageQuantityHint': '数量（例如：500）',
  'addMedicine.categoryLabel': '类别',
  'addMedicine.frequencyDurationLabel': '频率和持续时间',
  'addMedicine.selectDoseTimesPlaceholder': '选择剂量时间',
  'addMedicine.doseTimesBottomSheetTitle': '选择剂量时间',
  'addMedicine.timesSelectedInfo': '已选择 {count} 个时间',
  'addMedicine.selectDurationPlaceholder': '选择持续时间',
  'addMedicine.durationSelectedInfo': '{count} 天',
  'addMedicine.whenToTakeLabelText': '何时服用',
  'addMedicine.beforeFoodOption': '饭前',
  'addMedicine.afterFoodOption': '饭后',
  'addMedicine.notificationsSectionLabel': '通知',
  'addMedicine.notificationSubtext': '在每次服药前5分钟收到通知',
  'addMedicine.durationPickerTitle': '选择持续时间（天）',
  'addMedicine.durationPickerItemText': '{days} 天',
  'addMedicine.timesSelected': '次已选择',
  'addMedicine.notificationsLabel': '通知',
  'addMedicine.enableDoseReminders': '启用剂量提醒',
  'addMedicine.remindersSubtext': '在每次服药前5分钟收到通知',

  // Profile Page
  'personal_info': '个人信息',
  'preferences': '偏好设置',
  'about_app': '关于应用',
  'app_version': '应用版本',
  'privacy_policy': '隐私政策',
  'developer': '开发者：Furkan Akif İŞLEK',
  'noEmail': '未找到电子邮箱',
  'version.number': '1.0.0',
  'profile.deleteAccountImportant': '删除账户',
  'profile.deleteAccountImportantText': '您确定要删除您的账户吗？此操作无法撤销。',
  'profile.cancel': '取消',
  'profile.delete': '删除',
  'profile.errorDeletingAccount': '删除账户时出错',
  'profile.deleteAccountButton': '删除账户',

  // Profile Page
  'logout': '退出登录',
  'account': '账户',
};
