// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3eUrfVvbxw10oC-ES1nPHocu02nF4490',
    appId: '1:352808849408:web:87c171a792e5a4a59248e5',
    messagingSenderId: '352808849408',
    projectId: 'mdrm-b334b',
    authDomain: 'mdrm-b334b.firebaseapp.com',
    storageBucket: 'mdrm-b334b.firebasestorage.app',
    measurementId: 'G-G8ZNH93YZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaRwxWFKTtR5dKdKgC45mHSF8vOdQOic',
    appId: '1:352808849408:android:c207a4fed11cbb819248e5',
    messagingSenderId: '352808849408',
    projectId: 'mdrm-b334b',
    storageBucket: 'mdrm-b334b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-h5gGzWKcmrJlHDRsJBLNC5d0U25l8G0',
    appId: '1:352808849408:ios:af5ddf6eaab22b1c9248e5',
    messagingSenderId: '352808849408',
    projectId: 'mdrm-b334b',
    storageBucket: 'mdrm-b334b.firebasestorage.app',
    iosBundleId: 'com.example.mr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-h5gGzWKcmrJlHDRsJBLNC5d0U25l8G0',
    appId: '1:352808849408:ios:af5ddf6eaab22b1c9248e5',
    messagingSenderId: '352808849408',
    projectId: 'mdrm-b334b',
    storageBucket: 'mdrm-b334b.firebasestorage.app',
    iosBundleId: 'com.example.mr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3eUrfVvbxw10oC-ES1nPHocu02nF4490',
    appId: '1:352808849408:web:107f129b65f8ddf59248e5',
    messagingSenderId: '352808849408',
    projectId: 'mdrm-b334b',
    authDomain: 'mdrm-b334b.firebaseapp.com',
    storageBucket: 'mdrm-b334b.firebasestorage.app',
    measurementId: 'G-ES6985CPBH',
  );
}
