// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvNSc6CmwSJ-zfxBPcrQTsEKq-PFcci0',
    appId: '1:947314173488:web:ce81a507f775ef0591aff5',
    messagingSenderId: '947314173488',
    projectId: 'aminadose-7d38f',
    authDomain: 'aminadose-7d38f.firebaseapp.com',
    storageBucket: 'aminadose-7d38f.firebasestorage.app',
    measurementId: 'G-8S9PYR6G7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqS93c5FJM9rlKX6WF-tkVqBTegUNLok',
    appId: '1:947314173488:android:ef3839e87d4e30ac91aff5',
    messagingSenderId: '947314173488',
    projectId: 'aminadose-7d38f',
    storageBucket: 'aminadose-7d38f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzSgaFypqNUGNDXUtu0Ds0Ox5QK-F3dw',
    appId: '1:947314173488:ios:c642ea4e6f51832491aff5',
    messagingSenderId: '947314173488',
    projectId: 'aminadose-7d38f',
    storageBucket: 'aminadose-7d38f.firebasestorage.app',
    iosBundleId: 'com.aminadose.mr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBzSgaFypqNUGNDXUtu0Ds0Ox5QK-F3dw',
    appId: '1:947314173488:ios:c642ea4e6f51832491aff5',
    messagingSenderId: '947314173488',
    projectId: 'aminadose-7d38f',
    storageBucket: 'aminadose-7d38f.firebasestorage.app',
    iosBundleId: 'com.aminadose.mr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXvNSc6CmwSJ-zfxBPcrQTsEKq-PFcci0',
    appId: '1:947314173488:web:55b881da0bc742c091aff5',
    messagingSenderId: '947314173488',
    projectId: 'aminadose-7d38f',
    authDomain: 'aminadose-7d38f.firebaseapp.com',
    storageBucket: 'aminadose-7d38f.firebasestorage.app',
    measurementId: 'G-EQSNZJZSYM',
  );
}
